/** GENERATED by tools/registry.mjs from the App Galaxy registry (galaxy.json). Do not edit.
 * Public-safe subset: IDs, names, stacks, repo slugs, statuses and relations only. */
import type {Registry} from './registry.ts';
export const REGISTRY:Registry={
 "format": "galaxy-navigator.registry",
 "version": 1,
 "source": {
  "name": "galaxy.json (App Galaxy registry)",
  "generated": "2026-09-25",
  "updated": "2026-10-01T14:00:00"
 },
 "nodes": [
  {
   "id": "atlasnote",
   "name": "AtlasNote",
   "kind": "app",
   "stack": "React + Vite, Cloudflare Workers + Access, v2.3",
   "repo": "atlasnote",
   "hub": false
  },
  {
   "id": "claude-control",
   "name": "Claude Control",
   "kind": "app",
   "stack": "Python stdlib (local server + builders) + HTML pages",
   "repo": "claude-control",
   "hub": false
  },
  {
   "id": "data-xray",
   "name": "DataPass Data X-ray",
   "kind": "app",
   "stack": "VS Code extension / TypeScript / React webview / esbuild",
   "repo": "datapass-data-xray",
   "hub": false
  },
  {
   "id": "datapass",
   "name": "datapass",
   "kind": "repo",
   "stack": "",
   "repo": "datapass",
   "hub": false
  },
  {
   "id": "datapass-studio",
   "name": "datapass-studio",
   "kind": "repo",
   "stack": "",
   "repo": "datapass-studio",
   "hub": false
  },
  {
   "id": "datapass-vscode",
   "name": "DataPass VS Code",
   "kind": "app",
   "stack": "VS Code extension (TypeScript), v0.15.0",
   "repo": "datapass-vscode",
   "hub": false
  },
  {
   "id": "datapass-vscode-cloud",
   "name": "datapass-vscode-cloud",
   "kind": "repo",
   "stack": "",
   "repo": "datapass-vscode-cloud",
   "hub": false
  },
  {
   "id": "datapass-vscode-common",
   "name": "datapass-vscode-common",
   "kind": "repo",
   "stack": "",
   "repo": "datapass-vscode-common",
   "hub": false
  },
  {
   "id": "diagramcloud",
   "name": "DiagramCloud",
   "kind": "app",
   "stack": "React + Fluent UI + Vite",
   "repo": "diagramcloud",
   "hub": false
  },
  {
   "id": "effort-board",
   "name": "Effort Board (Claude workflow)",
   "kind": "app",
   "stack": "Python builders + HTML artifact",
   "repo": "",
   "hub": false
  },
  {
   "id": "foil",
   "name": "FOIL coordination",
   "kind": "app",
   "stack": "Docs + .datapass manifest",
   "repo": "foil-v1-vscode-datapass",
   "hub": false
  },
  {
   "id": "foil-study",
   "name": "FOIL STUDY",
   "kind": "app",
   "stack": "Python (PDF STUDY core, adapters cli / Azure Functions / ADF)",
   "repo": "foil-study",
   "hub": false
  },
  {
   "id": "mongoku",
   "name": "Mongoku (Datapass Mongo Control)",
   "kind": "app",
   "stack": "SvelteKit / Node / TypeScript",
   "repo": "Mongoku-datapass",
   "hub": true
  },
  {
   "id": "mosaic",
   "name": "Datapass Workbench (Mosaic)",
   "kind": "app",
   "stack": "VS Code extension + local server",
   "repo": "datapass-mosaic-vscode",
   "hub": false
  },
  {
   "id": "powerops",
   "name": "Power Ops (J Utility Palette)",
   "kind": "app",
   "stack": "C# / WPF (.NET)",
   "repo": "PowerToy_UI",
   "hub": false
  }
 ],
 "contracts": [
  {
   "id": "atlasnote.planning-overview/1",
   "name": "AtlasNote planning overview",
   "owner": "atlasnote",
   "consumers": [
    "mongoku",
    "powerops"
   ],
   "status": "live"
  },
  {
   "id": "claude-control-api",
   "name": "Claude Control local API on http://127.0.0.1:7430: GET /api/status[?project=], /api/project/<name>, /api/alerts, /api/health",
   "owner": "claude-control",
   "consumers": [
    "powerops",
    "mongoku",
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "claude-control-api.work-orders/1",
   "name": "GET /api/work-orders?ids=wo-…,wo-… (1–50 ids, else 400) → matched conversations per id; session fields tool/surface/cli_id/work_order",
   "owner": "claude-control",
   "consumers": [
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "claude-control-data-files",
   "name": "Dashboard data files: usage, history, sessions, timeline, backlog, team (.json) in effort-board, also served at http://127.0.0.1:7430/<file>.json",
   "owner": "claude-control",
   "consumers": [
    "effort-board",
    "powerops"
   ],
   "status": "planned"
  },
  {
   "id": "claude-control-inbox",
   "name": "inbox.jsonl: POST /api/inbox {to: supervisor|galaxy|design, text}",
   "owner": "claude-control",
   "consumers": [
    "claude-control"
   ],
   "status": "planned"
  },
  {
   "id": "claude-control-mongoku-panel",
   "name": "Mongoku \"Claude\" panel (flag, off by default) reading GET /api/status?project=Mongoku-datapass",
   "owner": "claude-control",
   "consumers": [
    "mongoku"
   ],
   "status": "live"
  },
  {
   "id": "claude-control-powerops-embed",
   "name": "Power Ops \"Claude Control\" tab: WebView2 embed of http://127.0.0.1:7430/home.html, Start action (tools/start-control.cmd), /api/health dot every 30 s",
   "owner": "claude-control",
   "consumers": [
    "powerops"
   ],
   "status": "branch"
  },
  {
   "id": "control_changesets",
   "name": "Mongoku control_* collections (control_changesets, control_revisions, control_meta, control_activity)",
   "owner": "mongoku",
   "consumers": [
    "mongoku"
   ],
   "status": "live"
  },
  {
   "id": "datapass-bridge-ai",
   "name": "Bridge V1 AI formats datapass.ai-context/1 and datapass.ai-plan/1",
   "owner": "diagramcloud",
   "consumers": [
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "datapass-common-public",
   "name": "Public contract repo julian-passebecq/datapass-vscode-common (schemas + bridge template), synced by npm run sync:common",
   "owner": "datapass-vscode",
   "consumers": [
    "foil"
   ],
   "status": "live"
  },
  {
   "id": "datapass-diagramcloud-sidecar",
   "name": ".datapass/diagramcloud.json sidecar (Bridge V1, format datapass.diagramcloud-sidecar)",
   "owner": "diagramcloud",
   "consumers": [
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "datapass-project-manifest",
   "name": ".datapass/project.json project manifest (v5 on main, since 0.18.0)",
   "owner": "datapass-vscode",
   "consumers": [
    "diagramcloud",
    "foil"
   ],
   "status": "live"
  },
  {
   "id": "datapass-vscode-deeplink",
   "name": "vscode://julian-passebecq.datapass-vscode/open?entity=<entity_id>",
   "owner": "datapass-vscode",
   "consumers": [
    "mongoku"
   ],
   "status": "retired"
  },
  {
   "id": "datapass.api-surface/1",
   "name": "DataPass API surface snapshot (decodeApiSurface output)",
   "owner": "datapass",
   "consumers": [
    "datapass-vscode-cloud"
   ],
   "status": "proposed"
  },
  {
   "id": "datapass.board/1",
   "name": ".datapass/board.json (DataPass board, version 1)",
   "owner": "datapass-vscode",
   "consumers": [
    "mongoku"
   ],
   "status": "planned"
  },
  {
   "id": "datapass.cloud-view-export/1",
   "name": "Cloud view export for other renderers (resolved view catalog, layout kinds, level captions; optional bound data per Location)",
   "owner": "datapass",
   "consumers": [
    "datapass-studio"
   ],
   "status": "proposed"
  },
  {
   "id": "datapass.cloud.lineage-diff/1",
   "name": "Diff between two lineage-graph/1 snapshots (added/removed/changed nodes and edges)",
   "owner": "datapass",
   "consumers": [
    "datapass-vscode-cloud"
   ],
   "status": "proposed"
  },
  {
   "id": "datapass.company-workspaces/1",
   "name": "Machine-local list of company workspace files (format datapass.company-workspaces v1) + open-view request (datapass.open-view v1)",
   "owner": "datapass-vscode",
   "consumers": [
    "powerops"
   ],
   "status": "planned"
  },
  {
   "id": "datapass.concept-entry/1",
   "name": "DataPass arch-catalog concept entry + taxonomy (exports CONSTRAINT_KINDS)",
   "owner": "datapass",
   "consumers": [
    "datapass-vscode-common",
    "datapass-vscode-cloud"
   ],
   "status": "proposed"
  },
  {
   "id": "datapass.lineage-drift/1",
   "name": "Static vs runtime lineage drift report (lineageDrift output)",
   "owner": "datapass",
   "consumers": [
    "datapass-vscode-cloud"
   ],
   "status": "proposed"
  },
  {
   "id": "datapass.pilot-request/1",
   "name": "Pilot requests/<n>.json -> responses/<n>.json",
   "owner": "datapass-vscode",
   "consumers": [
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "datapass.practice-answer-key/1",
   "name": "DataPass practice corpus answer key (cases, expected findings, precision gate)",
   "owner": "datapass",
   "consumers": [
    "datapass-vscode-common",
    "datapass-vscode-cloud"
   ],
   "status": "proposed"
  },
  {
   "id": "datapass.toolkit/1",
   "name": "DataPass toolkit catalogue: hub repo .datapass/toolkit/tools.json + recipes/*.json",
   "owner": "datapass-vscode",
   "consumers": [
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "datapass.work-log/1",
   "name": "Work log: <coordination repo>/.datapass/work-log.json + <private log repo>/work-logs/<project-id>.json (format datapass.work-log v1)",
   "owner": "datapass-vscode",
   "consumers": [
    "mongoku"
   ],
   "status": "live"
  },
  {
   "id": "datapass.work-order-marker/1",
   "name": "First prompt line \"DataPass work order <id>: read <path>\\order.md and follow it.\"",
   "owner": "datapass-vscode",
   "consumers": [
    "claude-control"
   ],
   "status": "live"
  },
  {
   "id": "datapass.work-order-result/1",
   "name": "Work order result.json written by the agent",
   "owner": "datapass-vscode",
   "consumers": [
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "datapass.work-order/1",
   "name": "DataPass work order (order.md + manifest) in <coordination repo>/.datapass/local/work-orders/<id>/",
   "owner": "datapass-vscode",
   "consumers": [
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "DATAPASSCONTROL",
   "name": "DATAPASSCONTROL database (entities, repositories, organizations, work_items, audit_runs)",
   "owner": "mongoku",
   "consumers": [
    "mongoku"
   ],
   "status": "live"
  },
  {
   "id": "decision-rationale/1",
   "name": "DataPass AI bridge decision rationale block (why/solves/how/alternatives)",
   "owner": "datapass",
   "consumers": [
    "datapass-vscode-common",
    "datapass-vscode-cloud"
   ],
   "status": "proposed"
  },
  {
   "id": "diagramcloud-deeplink",
   "name": "DiagramCloud deep link ?project=<id>&view=<id>&node=<id>",
   "owner": "diagramcloud",
   "consumers": [
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "diagramcloud.portfolio-index/1",
   "name": "DiagramCloud portfolio index",
   "owner": "diagramcloud",
   "consumers": [
    "mongoku"
   ],
   "status": "live"
  },
  {
   "id": "effort-board-audits",
   "name": "Effort Board audits/ + todo.md + journal.md",
   "owner": "effort-board",
   "consumers": [
    "powerops"
   ],
   "status": "live"
  },
  {
   "id": "effort-board-usage.json",
   "name": "Effort Board usage.json",
   "owner": "effort-board",
   "consumers": [
    "powerops"
   ],
   "status": "branch"
  },
  {
   "id": "foil-study-layout",
   "name": "foil-study folders + contracts/study-page.v1 fields, mirrored by the FOIL bridge (.datapass/graph.json, .datapass/sheet.json)",
   "owner": "foil-study",
   "consumers": [
    "foil"
   ],
   "status": "live"
  },
  {
   "id": "mongoku-entity-url",
   "name": "Mongoku entity URL (mongoku.url + entity_id)",
   "owner": "mongoku",
   "consumers": [
    "powerops"
   ],
   "status": "live"
  },
  {
   "id": "mongoku-reports-http",
   "name": "Mongoku report API /api/datapass/reports/{MAINTENANCE,...} and /api/datapass/workspace",
   "owner": "mongoku",
   "consumers": [
    "powerops"
   ],
   "status": "branch"
  },
  {
   "id": "mongoku.portfolio-context",
   "name": "mongoku.portfolio-context (bounded AI context)",
   "owner": "mongoku",
   "consumers": [],
   "status": "no-consumer"
  },
  {
   "id": "powerops-vault",
   "name": "Secrets boundary: secret values live only in the Power Ops vault",
   "owner": "powerops",
   "consumers": [
    "datapass-vscode",
    "atlasnote",
    "mongoku"
   ],
   "status": "live"
  },
  {
   "id": "powerops.atlasnote-handoff/1",
   "name": "Power Ops -> AtlasNote handoff JSON (+ atlasnote.import-receipt/1)",
   "owner": "powerops",
   "consumers": [
    "atlasnote"
   ],
   "status": "branch"
  },
  {
   "id": "projection-envelope",
   "name": "Galaxy projection envelope <app>.<name>/<major>",
   "owner": "mongoku",
   "consumers": [
    "atlasnote",
    "diagramcloud",
    "datapass-vscode"
   ],
   "status": "live"
  },
  {
   "id": "quick-actions.json",
   "name": "Power Ops quick-actions.json (powerops-quick-actions v1)",
   "owner": "powerops",
   "consumers": [
    "powerops"
   ],
   "status": "branch"
  }
 ],
 "edges": [
  {
   "id": "atlasnote>mongoku:atlasnote.planning-overview/1",
   "from": "atlasnote",
   "to": "mongoku",
   "contract": "atlasnote.planning-overview/1",
   "kind": "projection-export",
   "status": "live"
  },
  {
   "id": "atlasnote>mongoku:projection-envelope",
   "from": "atlasnote",
   "to": "mongoku",
   "contract": "projection-envelope",
   "kind": "schema",
   "status": "live"
  },
  {
   "id": "atlasnote>powerops:atlasnote.planning-overview/1",
   "from": "atlasnote",
   "to": "powerops",
   "contract": "atlasnote.planning-overview/1",
   "kind": "file-import",
   "status": "live"
  },
  {
   "id": "claude-control>claude-control:claude-control-inbox",
   "from": "claude-control",
   "to": "claude-control",
   "contract": "claude-control-inbox",
   "kind": "file",
   "status": "planned"
  },
  {
   "id": "claude-control>datapass-vscode:claude-control-api",
   "from": "claude-control",
   "to": "datapass-vscode",
   "contract": "claude-control-api",
   "kind": "http",
   "status": "live"
  },
  {
   "id": "claude-control>datapass-vscode:claude-control-api.work-orders/1",
   "from": "claude-control",
   "to": "datapass-vscode",
   "contract": "claude-control-api.work-orders/1",
   "kind": "http",
   "status": "live"
  },
  {
   "id": "claude-control>effort-board:claude-control-data-files",
   "from": "claude-control",
   "to": "effort-board",
   "contract": "claude-control-data-files",
   "kind": "file",
   "status": "planned"
  },
  {
   "id": "claude-control>mongoku:claude-control-api",
   "from": "claude-control",
   "to": "mongoku",
   "contract": "claude-control-api",
   "kind": "",
   "status": "live"
  },
  {
   "id": "claude-control>mongoku:claude-control-mongoku-panel",
   "from": "claude-control",
   "to": "mongoku",
   "contract": "claude-control-mongoku-panel",
   "kind": "http",
   "status": "live"
  },
  {
   "id": "claude-control>powerops:claude-control-api",
   "from": "claude-control",
   "to": "powerops",
   "contract": "claude-control-api",
   "kind": "http",
   "status": "live"
  },
  {
   "id": "claude-control>powerops:claude-control-data-files",
   "from": "claude-control",
   "to": "powerops",
   "contract": "claude-control-data-files",
   "kind": "",
   "status": "planned"
  },
  {
   "id": "claude-control>powerops:claude-control-powerops-embed",
   "from": "claude-control",
   "to": "powerops",
   "contract": "claude-control-powerops-embed",
   "kind": "embed",
   "status": "branch"
  },
  {
   "id": "datapass-vscode>claude-control:datapass.work-order-marker/1",
   "from": "datapass-vscode",
   "to": "claude-control",
   "contract": "datapass.work-order-marker/1",
   "kind": "work-order",
   "status": "live"
  },
  {
   "id": "datapass-vscode>datapass-vscode:datapass.pilot-request/1",
   "from": "datapass-vscode",
   "to": "datapass-vscode",
   "contract": "datapass.pilot-request/1",
   "kind": "",
   "status": "live"
  },
  {
   "id": "datapass-vscode>datapass-vscode:datapass.toolkit/1",
   "from": "datapass-vscode",
   "to": "datapass-vscode",
   "contract": "datapass.toolkit/1",
   "kind": "",
   "status": "live"
  },
  {
   "id": "datapass-vscode>datapass-vscode:datapass.work-order-result/1",
   "from": "datapass-vscode",
   "to": "datapass-vscode",
   "contract": "datapass.work-order-result/1",
   "kind": "",
   "status": "live"
  },
  {
   "id": "datapass-vscode>datapass-vscode:datapass.work-order/1",
   "from": "datapass-vscode",
   "to": "datapass-vscode",
   "contract": "datapass.work-order/1",
   "kind": "",
   "status": "live"
  },
  {
   "id": "datapass-vscode>diagramcloud:datapass-project-manifest",
   "from": "datapass-vscode",
   "to": "diagramcloud",
   "contract": "datapass-project-manifest",
   "kind": "file",
   "status": "live"
  },
  {
   "id": "datapass-vscode>diagramcloud:diagramcloud-deeplink",
   "from": "datapass-vscode",
   "to": "diagramcloud",
   "contract": "diagramcloud-deeplink",
   "kind": "deep-link",
   "status": "live"
  },
  {
   "id": "datapass-vscode>foil:datapass-common-public",
   "from": "datapass-vscode",
   "to": "foil",
   "contract": "datapass-common-public",
   "kind": "schema",
   "status": "live"
  },
  {
   "id": "datapass-vscode>foil:datapass-project-manifest",
   "from": "datapass-vscode",
   "to": "foil",
   "contract": "datapass-project-manifest",
   "kind": "",
   "status": "live"
  },
  {
   "id": "datapass-vscode>mongoku:datapass-vscode-deeplink",
   "from": "datapass-vscode",
   "to": "mongoku",
   "contract": "datapass-vscode-deeplink",
   "kind": "",
   "status": "retired"
  },
  {
   "id": "datapass-vscode>mongoku:datapass.board/1",
   "from": "datapass-vscode",
   "to": "mongoku",
   "contract": "datapass.board/1",
   "kind": "github-file",
   "status": "planned"
  },
  {
   "id": "datapass-vscode>mongoku:datapass.work-log/1",
   "from": "datapass-vscode",
   "to": "mongoku",
   "contract": "datapass.work-log/1",
   "kind": "github-file",
   "status": "live"
  },
  {
   "id": "datapass-vscode>powerops:datapass.company-workspaces/1",
   "from": "datapass-vscode",
   "to": "powerops",
   "contract": "datapass.company-workspaces/1",
   "kind": "file",
   "status": "planned"
  },
  {
   "id": "datapass>datapass-studio:datapass.cloud-view-export/1",
   "from": "datapass",
   "to": "datapass-studio",
   "contract": "datapass.cloud-view-export/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-cloud:datapass.api-surface/1",
   "from": "datapass",
   "to": "datapass-vscode-cloud",
   "contract": "datapass.api-surface/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-cloud:datapass.cloud.lineage-diff/1",
   "from": "datapass",
   "to": "datapass-vscode-cloud",
   "contract": "datapass.cloud.lineage-diff/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-cloud:datapass.concept-entry/1",
   "from": "datapass",
   "to": "datapass-vscode-cloud",
   "contract": "datapass.concept-entry/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-cloud:datapass.lineage-drift/1",
   "from": "datapass",
   "to": "datapass-vscode-cloud",
   "contract": "datapass.lineage-drift/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-cloud:datapass.practice-answer-key/1",
   "from": "datapass",
   "to": "datapass-vscode-cloud",
   "contract": "datapass.practice-answer-key/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-cloud:decision-rationale/1",
   "from": "datapass",
   "to": "datapass-vscode-cloud",
   "contract": "decision-rationale/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-common:datapass.concept-entry/1",
   "from": "datapass",
   "to": "datapass-vscode-common",
   "contract": "datapass.concept-entry/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-common:datapass.practice-answer-key/1",
   "from": "datapass",
   "to": "datapass-vscode-common",
   "contract": "datapass.practice-answer-key/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "datapass>datapass-vscode-common:decision-rationale/1",
   "from": "datapass",
   "to": "datapass-vscode-common",
   "contract": "decision-rationale/1",
   "kind": "",
   "status": "proposed"
  },
  {
   "id": "diagramcloud>datapass-vscode:datapass-bridge-ai",
   "from": "diagramcloud",
   "to": "datapass-vscode",
   "contract": "datapass-bridge-ai",
   "kind": "schema",
   "status": "live"
  },
  {
   "id": "diagramcloud>datapass-vscode:datapass-diagramcloud-sidecar",
   "from": "diagramcloud",
   "to": "datapass-vscode",
   "contract": "datapass-diagramcloud-sidecar",
   "kind": "file",
   "status": "live"
  },
  {
   "id": "diagramcloud>datapass-vscode:diagramcloud-deeplink",
   "from": "diagramcloud",
   "to": "datapass-vscode",
   "contract": "diagramcloud-deeplink",
   "kind": "",
   "status": "live"
  },
  {
   "id": "diagramcloud>mongoku:diagramcloud.portfolio-index/1",
   "from": "diagramcloud",
   "to": "mongoku",
   "contract": "diagramcloud.portfolio-index/1",
   "kind": "projection-export",
   "status": "live"
  },
  {
   "id": "diagramcloud>mongoku:projection-envelope",
   "from": "diagramcloud",
   "to": "mongoku",
   "contract": "projection-envelope",
   "kind": "schema",
   "status": "live"
  },
  {
   "id": "effort-board>powerops:effort-board-audits",
   "from": "effort-board",
   "to": "powerops",
   "contract": "effort-board-audits",
   "kind": "file",
   "status": "live"
  },
  {
   "id": "effort-board>powerops:effort-board-usage.json",
   "from": "effort-board",
   "to": "powerops",
   "contract": "effort-board-usage.json",
   "kind": "file",
   "status": "branch"
  },
  {
   "id": "foil-study>foil:foil-study-layout",
   "from": "foil-study",
   "to": "foil",
   "contract": "foil-study-layout",
   "kind": "file",
   "status": "live"
  },
  {
   "id": "foil>datapass-vscode:datapass-project-manifest",
   "from": "foil",
   "to": "datapass-vscode",
   "contract": "datapass-project-manifest",
   "kind": "file",
   "status": "live"
  },
  {
   "id": "mongoku>atlasnote:projection-envelope",
   "from": "mongoku",
   "to": "atlasnote",
   "contract": "projection-envelope",
   "kind": "",
   "status": "live"
  },
  {
   "id": "mongoku>datapass-vscode:projection-envelope",
   "from": "mongoku",
   "to": "datapass-vscode",
   "contract": "projection-envelope",
   "kind": "",
   "status": "live"
  },
  {
   "id": "mongoku>diagramcloud:projection-envelope",
   "from": "mongoku",
   "to": "diagramcloud",
   "contract": "projection-envelope",
   "kind": "",
   "status": "live"
  },
  {
   "id": "mongoku>mongoku:control_changesets",
   "from": "mongoku",
   "to": "mongoku",
   "contract": "control_changesets",
   "kind": "",
   "status": "live"
  },
  {
   "id": "mongoku>mongoku:DATAPASSCONTROL",
   "from": "mongoku",
   "to": "mongoku",
   "contract": "DATAPASSCONTROL",
   "kind": "mongo-read",
   "status": "live"
  },
  {
   "id": "mongoku>powerops:mongoku-entity-url",
   "from": "mongoku",
   "to": "powerops",
   "contract": "mongoku-entity-url",
   "kind": "",
   "status": "live"
  },
  {
   "id": "mongoku>powerops:mongoku-reports-http",
   "from": "mongoku",
   "to": "powerops",
   "contract": "mongoku-reports-http",
   "kind": "http",
   "status": "branch"
  },
  {
   "id": "powerops>atlasnote:powerops-vault",
   "from": "powerops",
   "to": "atlasnote",
   "contract": "powerops-vault",
   "kind": "rule",
   "status": "live"
  },
  {
   "id": "powerops>atlasnote:powerops.atlasnote-handoff/1",
   "from": "powerops",
   "to": "atlasnote",
   "contract": "powerops.atlasnote-handoff/1",
   "kind": "handoff-json",
   "status": "branch"
  },
  {
   "id": "powerops>datapass-vscode:powerops-vault",
   "from": "powerops",
   "to": "datapass-vscode",
   "contract": "powerops-vault",
   "kind": "rule",
   "status": "live"
  },
  {
   "id": "powerops>mongoku:powerops-vault",
   "from": "powerops",
   "to": "mongoku",
   "contract": "powerops-vault",
   "kind": "",
   "status": "live"
  },
  {
   "id": "powerops>powerops:quick-actions.json",
   "from": "powerops",
   "to": "powerops",
   "contract": "quick-actions.json",
   "kind": "",
   "status": "branch"
  }
 ]
};
