import {defineApp} from '../../src/framework/index.ts';
import {motionFields, motionBlock} from '../../src/framework/motion/index.ts';
import {demoArchitecture} from '../../src/architecture/demo.ts';
import {walkthrough} from './walkthrough.ts';
export default defineApp({manifest:{format:'datapass.web-app',schemaVersion:1,id:'architecture-reference',version:'0.3.0',title:'Architecture / reference app',label:'Synthetic framework acceptance client',description:'A stakeholder-facing application using the already qualified architecture review module.',theme:{accent:'#5f658e',density:'compact'},fields:[...motionFields(walkthrough,'arch')],datasets:[],tasks:[],pages:[
  {id:'review',title:'System review',description:'The existing review canvas is now a client-configured block. The browser does not query or modify a live system.',sections:[{id:'system',columns:1,blocks:[{id:'architecture',type:'architecture',resource:'system'}]}]},
  {id:'walkthrough',title:'Guided walkthrough',description:'Follow one illustrative batch step by step. The walkthrough and the review canvas share one selected component; source excerpts are inert text from the synthetic architecture document.',sections:[{id:'guided',columns:1,blocks:[motionBlock('walkthrough-motion','walkthrough','arch')]},{id:'shared-review',title:'Same selection in the review canvas',columns:1,blocks:[{id:'walkthrough-review',type:'architecture',resource:'system',selection:'arch-selection'}]}]},
  {id:'scope',title:'Scope',description:'Evidence and implementation boundaries stay visible.',sections:[{id:'scope-text',columns:1,blocks:[{id:'scope-note',type:'text',title:'A website over artifacts',text:'This client supplies an inert architecture document. The framework supplies navigation, state review, layout and lazy component registration. The existing architecture module supplies the canvas, schema comparison and report exports. The guided walkthrough reuses the motion capability (SVG/D3 with the pinned VizForge player) over the same document.',tone:'lead'},{id:'truth-note',type:'text',tone:'note',text:'All example nodes, schema differences and walkthrough steps are synthetic. There is no repository crawler, live warehouse connection, source execution or automatic publication.'}]}]}
]},bindings:{},resources:{architectures:{system:demoArchitecture},motions:{walkthrough}}});
