/** Fresh client-owned template data. Never copies another client's source or assets. */
export function explorerTemplate({id,title,template}){
  const spatial=template==='spatial';
  const content={format:'datapass.explorer',version:1,title,description:'A system, its components and the documents that explain them.',provenance:'synthetic',groups:[{id:'delivery',label:'Delivery'},{id:'research',label:'Research'}],facets:[{id:'purpose',label:'Purpose'},{id:'evidence',label:'Evidence'}],items:[
    {id:'platform',label:'Platform',kind:'Component',parent:null,group:'delivery',summary:'The first building block.',description:'Replace this description with approved client content.',tags:['Architecture'],position:[0,0],facts:[{label:'Source',value:'Synthetic starter'}],...(spatial?{scene:{entity:'platform',camera:'platform'}}:{})},
    {id:'analysis',label:'Analysis',kind:'Component',parent:null,group:'research',summary:'The second building block.',description:'Explain what this part contributes without inventing performance claims.',tags:['Data'],position:[260,0],facts:[],...(spatial?{scene:{entity:'analysis',camera:'analysis'}}:{})}
  ],documents:[
    {id:'platform-purpose',item:'platform',facet:'purpose',title:'Platform overview',summary:'A first client-owned document.',provenance:'synthetic',source:'Starter content; replace before publication',sections:[{title:'Purpose',text:'Describe the problem, the boundaries and the work behind this component.'}]},
    {id:'analysis-evidence',item:'analysis',facet:'evidence',title:'Analysis notes',summary:'A separate evidence facet.',provenance:'synthetic',source:'Starter content; not a measured result',sections:[{title:'Evidence and limits',text:'Attach only approved evidence. An authored illustration is not an execution receipt.'}]}
  ],journey:['platform','analysis'],...(spatial?{scene:'model',overviewCamera:'overview'}:{})};
  const primitive=(id,entity,x,color)=>({id,parent:null,entity,shape:'box',size:[2,2,2],position:[x,1,0],rotation:[0,0,0],explode:[0,1,0],color});
  const scene={format:'datapass.scene3d',version:1,title:'Starter assembly',note:'Generic original geometry, not a production model.',entities:[{id:'platform',label:'Platform',description:'The first component.'},{id:'analysis',label:'Analysis',description:'The second component.'}],parts:[primitive('platform-box','platform',-2,'#438eae'),primitive('analysis-box','analysis',2,'#9a7eb5')],cameras:[{id:'overview',label:'Overview',position:[10,8,12],target:[0,1,0]},{id:'platform',label:'Platform',position:[3,4,6],target:[-2,1,0]},{id:'analysis',label:'Analysis',position:[7,4,6],target:[2,1,0]}]};
  const files={'content.ts':`import type {ExplorerSpec} from '../../src/framework/index.ts';\nexport const content:ExplorerSpec=${JSON.stringify(content,null,2)};\n`};
  if(spatial)files['scene.ts']=`import type {SceneSpec} from '../../src/framework/index.ts';\nexport const scene:SceneSpec=${JSON.stringify(scene,null,2)};\n`;
  files['app.ts']=`import {defineApp,explorerFields,explorerBlock} from '../../src/framework/index.ts';\nimport {content} from './content.ts';\n${spatial?"import {scene} from './scene.ts';\n":''}export default defineApp({manifest:{format:'datapass.web-app',schemaVersion:1,id:${JSON.stringify(id)},version:'0.1.0',title:${JSON.stringify(title)},label:'Synthetic starter',description:'A client-owned ${spatial?'spatial explorer':'knowledge library'}.',theme:{accent:'${spatial?'#74c4e5':'#286b7d'}',density:'compact',mode:'${spatial?'dark':'light'}'},fields:explorerFields(content,'context','${spatial?'spatial':'library'}'),datasets:[],tasks:[],pages:[{id:'overview',title:'Explore',description:'Select a component, switch facets, or find a document.',sections:[{id:'content',columns:1,blocks:[explorerBlock('explorer','content','context',${spatial})]}]}]},bindings:{},resources:{explorers:{content}${spatial?',scenes:{model:scene}':''}}});\n`;
  return files;
}
