import test from 'node:test';
import assert from 'node:assert/strict';
import {SiteRuntime,validateDefinition,validateExplorer,explorerFields,explorerBlock,validateExplorerState,readExplorerState,explorerStatePatch,validateExplanation} from '../src/framework/index.ts';
import {navigateExplorer,ancestors,contextDocuments,explorerCamera,journeyStops,chapterAt,searchExplorer,explorerLink,readExplorerLink} from '../src/framework/explorer/navigation.ts';
import app from '../clients/experience-reference/app.ts';
import {atlas} from '../clients/experience-reference/atlas.ts';
import {stableOrder} from '../clients/experience-reference/explanation.ts';
const copy=()=>structuredClone(atlas);
const definition=()=>({...app,manifest:structuredClone(app.manifest),resources:structuredClone(app.resources)});
const block=app.manifest.pages[0].sections[0].blocks[0];
const initial={focus:'overview',facet:'skills',view:'spatial',level:'overview',group:'all',document:'none'};
function transition(state,action){return navigateExplorer(atlas,state,action);}
test('explorer source validates and is defensively cloned',()=>{const input=copy(),result=validateExplorer(input);input.items[0].label='changed';assert.notEqual(result.items[0].label,input.items[0].label);assert.equal(result.items.length,8);});
test('explorer field helpers construct exact view-only bindings',()=>{const fs=explorerFields(atlas,'v');assert.equal(fs.length,6);assert.ok(fs.every(f=>f.role==='view'));assert.equal(explorerBlock('a','r','v').focus,'v-focus');});
test('explorer navigation selects atomically without changing its source',()=>{const old=JSON.stringify(atlas),state=transition(initial,{type:'select',id:'cloud'});assert.equal(state.focus,'cloud');assert.equal(state.level,'focus');assert.equal(initial.focus,'overview');assert.equal(JSON.stringify(atlas),old);});
test('view switches keep the selected object and facet',()=>{let s=transition(initial,{type:'select',id:'cloud'});s=transition(s,{type:'facet',id:'projects'});s=transition(s,{type:'view',value:'map'});assert.equal(s.focus,'cloud');assert.equal(s.facet,'projects');assert.equal(s.view,'map');});
test('facet changes choose the authored camera, without introducing geometry',()=>{const s=transition(initial,{type:'select',id:'cloud'});assert.equal(explorerCamera(atlas,s),'cloud-front');assert.equal(explorerCamera(atlas,transition(s,{type:'facet',id:'projects'})),'cloud-side');assert.equal(explorerCamera(atlas,initial),'overview');});
test('context documents use explicit ancestry and facet',()=>{const s=transition(initial,{type:'select',id:'cloud'});assert.deepEqual(contextDocuments(atlas,s).map(d=>d.id),['cloud-skills']);assert.deepEqual(contextDocuments(atlas,transition(s,{type:'facet',id:'projects'})).map(d=>d.id),['pipeline-case']);});
test('opening a document establishes coherent item, facet, level and library context',()=>{const s=transition(initial,{type:'document',id:'pipeline-evidence'});assert.deepEqual(s,{focus:'pipeline',facet:'evidence',view:'library',level:'evidence',group:'all',document:'pipeline-evidence'});});
test('changing facet clears the previously selected document',()=>{const s=transition(transition(initial,{type:'document',id:'pipeline-evidence'}),{type:'facet',id:'projects'});assert.equal(s.document,'none');});
test('group filtering cannot leave a hidden object selected',()=>{const s=transition(transition(initial,{type:'select',id:'cloud'}),{type:'group',id:'analytics'});assert.equal(s.focus,'overview');assert.equal(s.level,'overview');assert.equal(s.group,'analytics');});
test('explicitly selecting an out-of-domain item resets the domain filter',()=>{const s=transition(transition(initial,{type:'group',id:'analytics'}),{type:'select',id:'cloud'});assert.equal(s.focus,'cloud');assert.equal(s.group,'all');});
test('overview is not an evidence state and detail needs a selection',()=>{assert.throws(()=>transition(initial,{type:'level',value:'evidence'}));assert.throws(()=>validateExplorerState(atlas,{...initial,level:'focus'}));});
test('runtime rejects cross-field incoherence before applying any patch',()=>{const r=new SiteRuntime(app),before=r.getSnapshot();assert.throws(()=>r.patch({[block.focus]:'cloud'}),/disagree/);assert.equal(r.getSnapshot(),before);r.patch(explorerStatePatch(block,transition(initial,{type:'select',id:'cloud'})));assert.equal(readExplorerState(block,r.getSnapshot().values).focus,'cloud');});
test('saved state validates explorer coherence as well as individual values',()=>{const r=new SiteRuntime(app),saved=r.save('explore');saved.values[block.focus]='cloud';assert.throws(()=>r.review(JSON.stringify(saved)),/disagree/);assert.equal(r.getSnapshot().values[block.focus],'overview');});
test('restoring reviewed explorer inputs is atomic and reset keeps defaults',()=>{const r=new SiteRuntime(app);r.patch(explorerStatePatch(block,transition(initial,{type:'document',id:'quality-evidence'})));const saved=r.save('explore');r.reset();assert.equal(r.getSnapshot().values[block.focus],'overview');r.restore(saved);assert.equal(r.getSnapshot().values[block.document],'quality-evidence');});
test('source defaults must themselves satisfy the joint explorer state',()=>{const d=definition();d.manifest.fields.find(f=>f.id===block.focus).default='cloud';assert.throws(()=>new SiteRuntime(d),/disagree/);});
test('unknown, non-string and duplicate content identities fail before rendering',()=>{for(const mutate of [d=>d.items.push(d.items[0]),d=>d.items[0].id='overview',d=>d.items[0].group=['platform'],d=>d.provenance=['synthetic'],d=>d.documents[0].item=['cloud'],d=>d.journey=[['cloud']]]){const d=copy();mutate(d);assert.throws(()=>validateExplorer(d));}});
test('hierarchy cycles, unknown parents and cross-domain ancestry are rejected',()=>{for(const mutate of [d=>d.items[0].parent='pipeline',d=>d.items[1].parent='missing',d=>d.items[1].group='analytics']){const d=copy();mutate(d);assert.throws(()=>validateExplorer(d));}});
test('hierarchy is returned from root to leaf with stable IDs',()=>{assert.deepEqual(ancestors(atlas,'pipeline').map(i=>i.id),['cloud','pipeline']);assert.deepEqual(ancestors(atlas,'overview'),[]);});
test('duplicate fact labels are rejected to preserve stable inspector identity',()=>{const d=copy();d.items[0].facts.push(d.items[0].facts[0]);assert.throws(()=>validateExplorer(d),/Duplicate fact/);});
test('unsupported executable and transport fields are rejected',()=>{for(const mutate of [d=>d.html='<script/>',d=>d.items[0].onClick='run()',d=>d.documents[0].sections[0].iframe='https://host',d=>d.items[0].scene.url='https://model']){const d=copy();mutate(d);assert.throws(()=>validateExplorer(d));}});
test('declared project destinations must exist and cannot be arbitrary URLs',()=>{const d=definition();d.resources.explorers.atlas.items[1].open.page='unknown';assert.throws(()=>validateDefinition(d),/destination/);d.resources.explorers.atlas.items[1].open.page='https://host';assert.throws(()=>validateDefinition(d));});
test('scene references validate actual entities and cameras',()=>{for(const mutate of [d=>d.items[0].scene.entity='missing',d=>d.items[0].scene.camera='missing',d=>d.items[0].scene.facetCameras.projects='missing',d=>d.overviewCamera='missing']){const d=definition();mutate(d.resources.explorers.atlas);assert.throws(()=>validateDefinition(d));}});
test('two content objects cannot silently alias the same pickable entity',()=>{const d=definition();d.resources.explorers.atlas.items[1].scene.entity='cloud';assert.throws(()=>validateDefinition(d),/distinct scene/);});
test('non-spatial libraries do not need a Three.js scene',()=>{const d=copy();delete d.scene;delete d.overviewCamera;d.items.forEach(i=>delete i.scene);validateExplorer(d);assert.equal(explorerFields(d)[2].default,'map');assert.equal(explorerCamera(d,{...initial,view:'library'}),null);assert.throws(()=>validateExplorerState(d,initial));});
test('explorer field options cannot drift from resource identities',()=>{const d=definition();d.manifest.fields.find(f=>f.id===block.focus).options.push({value:'extra',label:'Extra'});assert.throws(()=>validateDefinition(d),/options mismatch/);});
test('bindings must be distinct and view-owned',()=>{const d=definition();d.manifest.pages[0].sections[0].blocks[0].facet=block.focus;assert.throws(()=>validateDefinition(d));});
test('document bounds, unknown facets and repeated IDs fail',()=>{for(const mutate of [d=>d.documents.push(d.documents[0]),d=>d.documents[0].facet='missing',d=>d.documents[0].sections[0].text='x'.repeat(6001),d=>d.items[0].position=[Infinity,0]]){const d=copy();mutate(d);assert.throws(()=>validateExplorer(d));}});
test('local search uses text tokens, not user regular expressions',()=>{assert.ok(searchExplorer(atlas,'COUNT(*)').every(h=>h.kind==='document'));assert.deepEqual(searchExplorer(atlas,'[a-z]+'),[]);assert.equal(searchExplorer(atlas,'ingestion')[0].kind,'item');});
test('search respects domain, empty query and output budget',()=>{assert.deepEqual(searchExplorer(atlas,'pipeline','analytics'),[]);assert.deepEqual(searchExplorer(atlas,''),[]);assert.equal(searchExplorer(atlas,'synthetic','all',1).length,1);assert.throws(()=>searchExplorer(atlas,'a'.repeat(161)));});
test('search normalizes accents and returns stable identity instead of markup',()=>{const d=copy();d.items[0].label='Données';assert.equal(searchExplorer(d,'donnees')[0].id,'cloud');assert.throws(()=>searchExplorer(d,'x','unknown'));});
test('scroll chapters are bounded at both ends and on malformed input',()=>{assert.equal(chapterAt(-5,5),0);assert.equal(chapterAt(7,5),4);assert.equal(chapterAt(.5,5),2);assert.equal(chapterAt(.2,1),0);assert.throws(()=>chapterAt(NaN,5));assert.throws(()=>chapterAt(.5,0));});
test('journeys are explicitly declared and domain-filtered',()=>{assert.deepEqual(journeyStops(atlas,'analytics'),['overview','insights']);assert.equal(journeyStops(atlas).length,5);});
test('view links exclude unknown URL parameters, fragments, models and document bytes',()=>{const s=transition(initial,{type:'document',id:'pipeline-evidence'}),link=explorerLink('https://example.test/site?app=experience-reference&page=explore&token=SECRET#private','system-atlas',atlas,s);assert.ok(!link.includes('SECRET'));assert.ok(!link.includes('private'));assert.ok(!link.includes('SELECT'));assert.equal(new URL(link).searchParams.get('app'),'experience-reference');assert.deepEqual(readExplorerLink(link,'system-atlas',atlas,initial),s);});
test('view links reject credentials, unsafe protocols, duplicates and incoherent IDs',()=>{assert.throws(()=>explorerLink('https://user:password@example.test','a',atlas,initial));assert.throws(()=>explorerLink('javascript:x','a',atlas,initial));assert.throws(()=>readExplorerLink('https://test/?view-a-focus=cloud&view-a-focus=models','a',atlas,initial));assert.throws(()=>readExplorerLink('https://test/?view-a-document=missing','a',atlas,initial));});
test('URLs without an explorer state do not replace current inputs',()=>{assert.equal(readExplorerLink('https://test/?page=method','a',atlas,initial),null);});
test('context-dependent D3 data counts actual documents instead of fabricated performance',()=>{const r=new SiteRuntime(app);assert.equal(r.dataset('coverage').reduce((n,row)=>n+row.count,0),12);r.patch(explorerStatePatch(block,transition(initial,{type:'select',id:'cloud'})));assert.equal(r.dataset('coverage').reduce((n,row)=>n+row.count,0),3);assert.equal(r.dataset('context-summary')[0].count,2);});
test('changing an information facet does not invalidate unrelated coverage data',()=>{const r=new SiteRuntime(app),first=r.dataset('coverage');r.patch(explorerStatePatch(block,transition(initial,{type:'facet',id:'projects'})));assert.equal(r.dataset('coverage'),first);});
test('explanation preserves original loop structure and validates all frame references',()=>{const value=validateExplanation(stableOrder,app.manifest);assert.equal(value.spec.kind,'loop');assert.equal(value.spec.frames.length,4);assert.equal(value.spec.frames[3].variables.stable,true);});
test('explanation rejects non-scalar executable fields and unknown item/code refs',()=>{for(const mutate of [d=>d.spec.items[0].value={code:'eval()'},d=>d.spec.run='x',d=>d.spec.frames[0].pointerItemId='missing',d=>d.spec.frames[0].codeLineIds=['missing'],d=>d.spec.frames[0].order=['a','a','b','c']]){const d=structuredClone(stableOrder);mutate(d);assert.throws(()=>validateExplanation(d));}});
test('explanation field spans exactly the authored frames and never model inputs',()=>{const m=structuredClone(app.manifest);m.fields.find(f=>f.id==='explanationStep').max=100;assert.throws(()=>validateExplanation(stableOrder,m));m.fields.find(f=>f.id==='explanationStep').max=3;m.fields.find(f=>f.id==='explanationStep').role='input';assert.throws(()=>validateExplanation(stableOrder,m));});
test('explanation copies source, rejects duplicate IDs, and keeps code inert',()=>{const d=structuredClone(stableOrder),before=globalThis.explorerExecuted;d.spec.codeLines[0].text='globalThis.explorerExecuted=true';const value=validateExplanation(d);assert.equal(globalThis.explorerExecuted,before);d.spec.title='Changed';assert.notEqual(value.spec.title,d.spec.title);d.spec.items.push(d.spec.items[0]);assert.throws(()=>validateExplanation(d));});
test('fresh knowledge and spatial scaffolds are isolated client files',async()=>{
  const {scaffoldClient}=await import('../scripts/scaffold-client.mjs');const {mkdtemp,readFile,rm,readdir}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const path=await import('node:path');
  const root=await mkdtemp(path.join(tmpdir(),'studio-templates-'));
  try{for(const template of ['knowledge','spatial']){const target=await scaffoldClient({root,id:template,title:'Client "quoted" title',template});const source=await readFile(path.join(target,'app.ts'),'utf8');assert.ok(source.includes('explorerFields(content'));assert.ok(!source.includes('experience-reference'));const files=await readdir(target);assert.equal(files.includes('scene.ts'),template==='spatial');assert.ok(!files.includes('node_modules'));await assert.rejects(()=>scaffoldClient({root,id:template,template}));}}finally{await rm(root,{recursive:true,force:true});}
});
test('bad template options fail before leaving partially scaffolded clients',async()=>{
  const {scaffoldClient}=await import('../scripts/scaffold-client.mjs');const {mkdtemp,rm,readdir}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const path=await import('node:path');
  const root=await mkdtemp(path.join(tmpdir(),'studio-bad-template-'));try{await assert.rejects(()=>scaffoldClient({root,id:'test',template:'unknown'}));await assert.rejects(()=>scaffoldClient({root,id:'test',template:'spatial',custom:'invalid'}));assert.deepEqual(await readdir(root),[]);}finally{await rm(root,{recursive:true,force:true});}
});

test('explanation pointer references cannot coerce arrays into valid item IDs',()=>{const d=structuredClone(stableOrder);d.spec.frames[0].pointerItemId=['a'];assert.throws(()=>validateExplanation(d),/pointer item/);});
