import test from 'node:test';
import assert from 'node:assert/strict';
import {createNotebook,createCell,editNotebook,validateNotebook,parseNotebook,executionOrder,removeCell,dependentIds,toIpynb,fromIpynb,resultMatches} from '../src/workbench-v1/model.ts';
const base=()=>createNotebook('Blank','2026-10-10T00:00:00.000Z','test-notebook');
const cell=(id,language='sql',dependsOn=[])=>({...createCell(language,id),source:'SELECT 1',dependsOn});
test('blank means no examples, datasets or executable cells',()=>assert.deepEqual(base().cells,[]));
test('edits advance a validated revision',()=>{const n=editNotebook(base(),{cells:[cell('a')]});assert.equal(n.revision,1);assert.equal(n.cells.length,1);});
test('unknown imported fields are not permissions',()=>{const n=validateNotebook({...base(),trustedPython:true,outputs:[{secret:'x'}]});assert.equal('trustedPython' in n,false);assert.equal('outputs' in n,false);});
test('source limit is enforced before parse',()=>assert.throws(()=>parseNotebook(' '.repeat(2*1024*1024+1)),/limit/));
test('duplicate IDs rejected',()=>assert.throws(()=>editNotebook(base(),{cells:[cell('a'),cell('a')]}),/Duplicate/));
test('missing dependency rejected',()=>assert.throws(()=>executionOrder([cell('a','sql',['b'])]),/Missing/));
test('cycle rejected',()=>assert.throws(()=>executionOrder([cell('a','sql',['b']),cell('b','sql',['a'])]),/cycle/));
test('stable topological execution',()=>assert.deepEqual(executionOrder([cell('b','sql',['a']),cell('a'),cell('c')]).map(c=>c.id),['a','b','c']));
test('markdown cannot be a runtime dependency',()=>assert.throws(()=>executionOrder([cell('a','markdown'),cell('b','sql',['a'])]),/executable/));
test('removal cleans edges without deleting other cells',()=>{const n=editNotebook(base(),{cells:[cell('a'),cell('b','sql',['a'])]});assert.deepEqual(removeCell(n,'a').cells.map(c=>c.dependsOn),[[]]);});
test('transitive downstream invalidation',()=>assert.deepEqual([...dependentIds([cell('a'),cell('b','sql',['a']),cell('c','sql',['b']),cell('d')],'a')],['a','b','c']));
test('late result needs matching source',()=>{const c=cell('a');assert.equal(resultMatches(c,{cellId:'a',source:'SELECT 2'}),false);assert.equal(resultMatches(c,{cellId:'a',source:'SELECT 1'}),true);});
test('ipynb round trip preserves source and language but never outputs',()=>{const n=editNotebook(base(),{cells:[cell('a','sql'),cell('b','python',['a']),cell('c','markdown')]});const out=toIpynb(n);out.cells[0].outputs=[{text:'private'}];const back=fromIpynb(out);assert.deepEqual(back.cells,n.cells);assert.equal('outputs' in back.cells[0],false);});
test('unsafe identifiers and invalid dates rejected',()=>{assert.throws(()=>validateNotebook({...base(),id:'../secrets'}),/identifier/);assert.throws(()=>validateNotebook({...base(),createdAt:'yesterday'}),/ISO/);});
test('empty sources and unicode round trip',()=>{const n=editNotebook(base(),{title:'Oslo SQL',cells:[createCell('sql','blank')]});assert.deepEqual(parseNotebook(JSON.stringify(n)),n);});
