import {useEffect,useState} from 'react';
import {WorkspaceShell} from '../../src/framework/workspace';
import {SourceReader} from '../../src/framework/evidence/react';
import type {EvidenceRef} from '../../src/framework/evidence/model';
import type {SearchHit,ContextBundle,ContextSelection} from '../../src/framework/foundation/knowledge';
import {createBrowserHost} from '../../src/core/host';
import {knowledge,sources} from './knowledge';
import './reference.css';
export function KnowledgeDemo(){
  const [panel,setPanel]=useState('sources'),[selected,setSelected]=useState(sources[0].id),[highlights,setHighlights]=useState<EvidenceRef[]>([]);
  const [query,setQuery]=useState(''),[submitted,setSubmitted]=useState(''),[hits,setHits]=useState<readonly SearchHit[]>([]),[error,setError]=useState('');
  const [modes,setModes]=useState<Record<string,ContextSelection['mode']>>(()=>Object.fromEntries(sources.map(s=>[s.id,'excluded']))),[budget,setBudget]=useState(4096),[bundle,setBundle]=useState<ContextBundle|null>(null);
  useEffect(()=>{if(!submitted){setHits([]);return;}const abort=new AbortController();let active=true;knowledge.search(submitted,{signal:abort.signal}).then(result=>{if(active)setHits(result);}).catch(error=>{if(active&&error.name!=='AbortError')setError(String(error));});return()=>{active=false;abort.abort();};},[submitted]);
  function choose(id:string){setSelected(id);setPanel('sources');setHighlights([]);}
  async function prepare(){try{setBundle(await knowledge.context(sources.map(source=>({sourceId:source.id,mode:modes[source.id]})),budget));setError('');}catch(e){setError(String(e));}}
  return <section data-testid="knowledge-demo"><WorkspaceShell title="Approved source context" sidebar={<div className="reference-outline">{sources.map(source=><button key={source.id} type="button" aria-pressed={selected===source.id} onClick={()=>choose(source.id)}>{source.path}</button>)}</div>} inspector={<div className="reference-padding"><span className="foundation-kicker">Local provider</span><h3>Read, search, prepare</h3><p>These files were explicitly included in this synthetic client. Search is lexical, not semantic retrieval. Summaries were supplied by the author.</p><p>No context is sent to an AI or external service. Exclusion controls the prepared export, not access to files bundled in a public site.</p>{bundle&&<p data-testid="context-bytes">{bundle.byteLength} bytes / {budget} budget</p>}</div>} tabs={[{id:'sources',label:'Sources'},{id:'context',label:'Context for AI'}]} activeTab={panel} onTab={setPanel} status={<><span>Static source provider / exact line references</span><span>No ingestion, embedding database or LLM</span></>}>
      <form className="reference-search" onSubmit={e=>{e.preventDefault();setError('');setSubmitted(query.trim());}}><label>Search approved sources<input aria-label="Search approved sources" value={query} onChange={e=>setQuery(e.target.value)} maxLength={200}/></label><button type="submit">Search sources</button></form>
      {error&&<p role="alert">{error}</p>}
      {submitted&&<div className="reference-search-results" data-testid="source-search-results">{hits.length?hits.map(hit=><button type="button" key={hit.sourceId+':'+hit.reference.start} onClick={()=>{setSelected(hit.sourceId);setHighlights([hit.reference]);setPanel('sources');}}><strong>{hit.path}:{hit.reference.start}</strong><span>{hit.excerpt}</span></button>):<p>No matching source lines.</p>}</div>}
      {panel==='sources'?<SourceReader sources={sources} selected={selected} onSelect={choose} highlights={highlights}/>:<div className="reference-context-builder"><h3>Deliberate context, bounded by bytes</h3><p>All sources start excluded. Choose complete source or an authored summary, then prepare a local context bundle.</p>{sources.map(source=><label key={source.id}>{source.path}<select aria-label={'Context mode '+source.id} value={modes[source.id]} onChange={e=>{setModes({...modes,[source.id]:e.target.value as ContextSelection['mode']});setBundle(null);}}><option value="excluded">Excluded</option><option value="summary">Authored summary</option><option value="full">Full source</option></select></label>)}<label>Byte budget<input aria-label="Context byte budget" type="number" min={4096} max={65536} step={1024} value={budget} onChange={e=>{setBudget(Number(e.target.value));setBundle(null);}}/></label><button type="button" onClick={()=>void prepare()}>Prepare local context</button>{bundle&&<><pre data-testid="prepared-context">{JSON.stringify(bundle.payload,null,2)}</pre><button type="button" onClick={()=>createBrowserHost().saveDownload('approved-context.json',new Blob([JSON.stringify(bundle.payload,null,2)],{type:'application/json'}))}>Export prepared context JSON</button></>}</div>}
    </WorkspaceShell></section>;
}
