import {useEffect,useId,useState} from 'react';
import {useRuntime,useSiteState} from '../../src/framework/ui';
import {WorkspaceShell} from '../../src/framework/workspace';
import {ContextInspector} from '../../src/framework/foundation/ContextInspector';
import {readNavigation,navigationPatch,visibleEntities,navigationQuery,parseNavigationQuery} from '../../src/framework/foundation/navigation';
import {navigation} from './navigation';
import './reference.css';
const orbit:Record<string,[number,number]>={presentation:[330,72],calculation:[160,168],knowledge:[500,168],storage:[245,286],'external-api':[570,286]};
const dependency:Record<string,[number,number]>={presentation:[100,80],knowledge:[100,255],calculation:[295,80],storage:[500,80],'external-api':[600,255]};
export function NavigationDemo(){
  const runtime=useRuntime(),snapshot=useSiteState(),state=readNavigation(navigation,snapshot.values,'nav'),id=useId();
  const [error,setError]=useState('');
  const items=visibleEntities(navigation,state),selected=navigation.entities.find(e=>e.id===state.selection);
  function choose(selection:string){runtime.patch(navigationPatch(navigation,state,{selection},'nav'));}
  useEffect(()=>{try{const target=parseNavigationQuery(navigation,location.search);if(target)runtime.patch(navigationPatch(navigation,readNavigation(navigation,runtime.getSnapshot().values,'nav'),target,'nav'));}catch(e){setError(String(e));}},[runtime]);
  const url=new URL(location.href);new URLSearchParams(navigationQuery(navigation,state)).forEach((value,key)=>url.searchParams.set(key,value));
  const related=navigation.relations.filter(r=>r.from===state.selection||r.to===state.selection);
  const context={id:selected?.id||'overview',kind:selected?.external?'External integration':'Synthetic semantic context',title:selected?.label||'One system, several views',summary:selected?.summary||'Orbit, dependency and inventory views share the same entity identities.',facts:selected?[{label:'Ownership',value:selected.external?'External':'Internal'},{label:'Visible in facet',value:items.some(e=>e.id===selected.id)?'Yes':'No; selection is preserved'},{label:'Depth',value:state.depth}]:[],references:[],related:related.map(r=>{const target=navigation.entities.find(e=>e.id===(r.from===state.selection?r.to:r.from))!;return {id:target.id,label:target.label};}),note:state.depth==='evidence'?related.map(r=>r.kind+' / '+r.source).join('\n')||'No relationships are declared for this selection.':'This is a small synthetic navigation fixture, not the Galaxy application inventory.'};
  const positions=state.projection==='orbit'?orbit:dependency;
  return <section data-testid="semantic-navigation" data-selection={state.selection} data-projection={state.projection} data-depth={state.depth}>
    <WorkspaceShell title="Semantic navigation" sidebar={<div className="reference-outline"><button type="button" onClick={()=>choose('none')}>Overview</button>{navigation.entities.map(e=><button type="button" key={e.id} aria-label={'Inspect '+e.label} aria-pressed={e.id===state.selection} onClick={()=>choose(e.id)}>{e.label}{e.external?' / external':''}</button>)}</div>} inspector={<ContextInspector model={context} onRelated={choose}/>} tabs={navigation.projections.map(p=>({id:p.id,label:p.label}))} activeTab={state.projection} onTab={projection=>runtime.patch(navigationPatch(navigation,state,{projection},'nav'))} status={<><span>One semantic ID across all projections</span><span>No data task is run by navigation</span></>}>
      <div className="reference-navigation-controls"><label>Facet<select aria-label="Navigation facet" value={state.facet} onChange={e=>runtime.patch(navigationPatch(navigation,state,{facet:e.target.value},'nav'))}>{navigation.facets.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label><label>Depth<select aria-label="Navigation depth" value={state.depth} onChange={e=>runtime.patch(navigationPatch(navigation,state,{depth:e.target.value},'nav'))}>{navigation.depths.map((d,i)=><option key={d.id} value={d.id} disabled={i>0&&state.selection==='none'}>{d.label}</option>)}</select></label><a href={url.href}>Open this view link</a></div>
      {error&&<p role="alert">{error}</p>}
      {state.projection==='list'?<div className="reference-inventory">{items.map(e=><button key={e.id} type="button" onClick={()=>choose(e.id)} aria-pressed={e.id===state.selection}><strong>{e.label}</strong><span>{e.summary}</span><small>{e.external?'External integration':'Internal component'}</small></button>)}</div>:<div className="reference-graph"><svg viewBox="0 0 720 370" role="group" aria-label="Synthetic component relationships"><defs><marker id={id} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z"/></marker></defs>{navigation.relations.filter(r=>items.some(e=>e.id===r.from)&&items.some(e=>e.id===r.to)).map(r=>{const a=positions[r.from],b=positions[r.to];return <path key={r.id} d={`M${a[0]},${a[1]} L${b[0]},${b[1]}`} markerEnd={'url(#'+id+')'} className="reference-edge"><title>{r.kind} / {r.source}</title></path>;})}{items.map(e=>{const [x,y]=positions[e.id];return <g key={e.id} transform={`translate(${x},${y})`} role="button" tabIndex={0} aria-label={'Select '+e.label} aria-pressed={e.id===state.selection} onClick={()=>choose(e.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose(e.id);}}} className={'reference-node'+(e.external?' external':'')}><rect x="-78" y="-29" width="156" height="58" rx="9"/><text textAnchor="middle" y="-2">{e.label}</text><text textAnchor="middle" y="15" className="reference-node-kind">{e.external?'external provider':e.kind}</text></g>;})}</svg></div>}
      <p className="foundation-note reference-padding">The positions in this test client are authored. The framework supplies semantic state, not a new graph-layout engine. A production Galaxy view can use the existing React Flow or spatial renderer.</p>
    </WorkspaceShell>
  </section>;
}
