import {useEffect, useMemo, useRef, useState, memo, type ChangeEvent} from 'react';
import {ReactFlow, Background, Controls, Handle, Position, MarkerType, type Node, type NodeProps} from '@xyflow/react';
import {Button} from '../fluent';
import {FileUp, Download, Presentation, ArrowLeft, ArrowRight, X, Search, Network} from 'lucide-react';
import {createBrowserHost} from '../core/host';
import {parsePipeline} from '../core/pipeline';
import {ARCHITECTURE_LIMITS, readArtifactJson, record, validateArchitecture, compareColumns, graphFacts, neighborhood, layoutArchitecture, exportArchitecture, type Architecture as ArchitectureDocument, type ArchitectureNode} from '../architecture/model';
import {fromDbtManifest, fromPipeline, attachDbtCatalog} from '../architecture/adapters';
import {demoArchitecture} from '../architecture/demo';
import {architectureReport, architectureSvg} from '../architecture/export';
import '../architecture/architecture.css';

// Session-only continuity across SQLRooms module unmounts. Never persisted or uploaded.
let session: {doc: ArchitectureDocument; manifestMetadata?: Record<string, unknown>} = {doc: demoArchitecture};
type Pending = typeof session;
type DiagramData = {item: ArchitectureNode; mode: 'design' | 'snapshot'; active: boolean; dimmed: boolean};
const ArchitectureCard = memo(function ArchitectureCard({data}: NodeProps<Node<DiagramData>>) {
  const n = data.item, diff = compareColumns(n), cols = data.mode === 'design' ? n.logical : n.physical;
  return <div className={'arch-node ' + n.kind + (data.active ? ' active' : '') + (data.dimmed ? ' dimmed' : '')}>
    <Handle id="left" type="target" position={Position.Left}/><Handle id="top" type="target" position={Position.Top}/><div className="arch-node-kicker"><span>{n.kind}</span><span>{n.layer}</span></div>
    <strong>{n.label}</strong><div className="arch-node-fields">{cols ? cols.slice(0, 3).map(c => <div key={c.name}><span>{c.name}</span><code>{c.type}</code></div>) : <p>{data.mode === 'snapshot' ? 'No catalog schema supplied' : n.description.slice(0, 100)}</p>}{cols && cols.length > 3 && <small>+{cols.length - 3} fields</small>}</div>
    <footer><span>{n.owner || 'Owner not declared'}</span>{diff.changes.length > 0 && <b>{diff.changes.length} diffs</b>}</footer><Handle id="right" type="source" position={Position.Right}/><Handle id="bottom" type="source" position={Position.Bottom}/>
  </div>;
});
const nodeTypes = {architecture: ArchitectureCard};
function ImportReview({pending, apply, cancel}: {pending: Pending; apply(): void; cancel(): void}) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const d = ref.current!; d.showModal(); return () => d.close(); }, []);
  return <dialog ref={ref} className="arch-dialog" onCancel={cancel}><h2>Review architecture import</h2><p><strong>{pending.doc.title}</strong></p><p>{pending.doc.nodes.length} components / {pending.doc.edges.length} links. {pending.doc.snapshot ? pending.doc.snapshot.label : 'No catalog snapshot.'}</p><p>This replaces the current architecture view, not your files or database. Source text is inert. Imports stay in this browser session and disappear on reload.</p><p className="arch-muted">Export the current view first when it must be retained.</p><div><Button onClick={cancel}>Cancel</Button><Button appearance="primary" onClick={apply}>Apply architecture import</Button></div></dialog>;
}
function ColumnTable({node}: {node: ArchitectureNode}) {
  const columns = [...new Set([...(node.logical || []).map(c => c.name), ...(node.physical || []).map(c => c.name)])];
  if (!columns.length) return <p className="arch-muted">No column schema was supplied for this component.</p>;
  const changes = compareColumns(node);
  return <><p className="arch-muted">{changes.state === 'compared' ? `${changes.changes.length} differences / ${changes.unknown} unknown type or nullability comparisons` : changes.state === 'no-design' ? 'No declared design schema. No drift conclusion is possible.' : 'No catalog schema. Missing evidence is not a match.'}</p><div className="arch-table-scroll"><table><caption className="arch-sr">Design and catalog columns for {node.label}</caption><thead><tr><th>Column</th><th>Design</th><th>Snapshot</th></tr></thead><tbody>{columns.map(name => {const a = node.logical?.find(c => c.name === name), b = node.physical?.find(c => c.name === name);return <tr className={changes.changes.some(c => c.column === name) ? 'changed' : ''} key={name}><th scope="row">{name}</th><td>{a?.type || (node.logical === null ? 'Not supplied' : 'Absent')}</td><td>{b?.type || (node.physical === null ? 'Not supplied' : 'Absent')}</td></tr>;})}</tbody></table></div></>;
}
export default function Architecture() {
  const [current, setCurrent] = useState<Pending>(() => session), [pending, setPending] = useState<Pending | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [generation, setGeneration] = useState(0);
  const [selected, setSelected] = useState<string | null>(null), [query, setQuery] = useState(''), [direction, setDirection] = useState<'all' | 'upstream' | 'downstream'>('all');
  const [tab, setTab] = useState<'map' | 'drift' | 'matrix'>('map'), [mode, setMode] = useState<'design' | 'snapshot'>('design');
  const [present, setPresent] = useState(() => new URLSearchParams(location.search).get('present') === '1'), [chapter, setChapter] = useState(0), [includeSource, setIncludeSource] = useState(false), [matrixPage, setMatrixPage] = useState(0);
  const filePicker = useRef<HTMLInputElement>(null), catalogPicker = useRef<HTMLInputElement>(null);
  const doc = current.doc, facts = useMemo(() => graphFacts(doc), [doc]), positions = useMemo(() => layoutArchitecture(doc), [doc]);
  const node = doc.nodes.find(n => n.id === selected) || null;
  const upstream = useMemo(() => selected ? neighborhood(doc, selected, 'upstream') : new Set<string>(), [doc, selected]);
  const downstream = useMemo(() => selected ? neighborhood(doc, selected, 'downstream') : new Set<string>(), [doc, selected]);
  const chapters = useMemo(() => [{title: 'System overview', body: doc.description, ids: doc.nodes.map(n => n.id)}, ...doc.layers.map(layer => ({title: layer, body: doc.nodes.filter(n => n.layer === layer).map(n => n.label).join(' / '), ids: doc.nodes.filter(n => n.layer === layer).map(n => n.id)})), {title: 'Review before approval', body: `${facts.changes.length} schema differences across ${facts.compared} comparable components. ${facts.cycles.length} cyclic groups. These are artifact findings, not execution evidence.`, ids: [...new Set(facts.changes.map(c => c.nodeId))]}], [doc, facts]);
  const activeChapter = chapters[Math.min(chapter, chapters.length - 1)];
  useEffect(() => { document.body.classList.toggle('architecture-presenting', present); return () => document.body.classList.remove('architecture-presenting'); }, [present]);
  useEffect(() => { if (!present) return; const key = (e: KeyboardEvent) => {if ((e.target as HTMLElement)?.closest('input,textarea,select,dialog')) return; if (e.key === 'Escape') setPresent(false); if (e.key === 'ArrowRight') {e.preventDefault(); setChapter(c => Math.min(chapters.length - 1, c + 1));} if (e.key === 'ArrowLeft') {e.preventDefault(); setChapter(c => Math.max(0, c - 1));}}; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);}, [present, chapters.length]);
  function choose(id: string) {setSelected(id); setTab('map');}
  function applyImport() {if (!pending) return; session = pending; setCurrent(pending); setGeneration(g => g + 1); setPending(null); setSelected(null); setQuery(''); setChapter(0); setMatrixPage(0); setIncludeSource(false); setError('');}
  async function importFile(event: ChangeEvent<HTMLInputElement>, catalog: boolean) {
    const file = event.currentTarget.files?.[0]; event.currentTarget.value = ''; if (!file) return;
    setBusy(true); setError('');
    try {
      if (file.size > ARCHITECTURE_LIMITS.bytes || file.size === 0) throw new Error('Select a non-empty JSON artifact of at most 2 MiB');
      const source = await file.text(), value = readArtifactJson(source);
      if (catalog) {setPending({...current, doc: attachDbtCatalog(doc, value, current.manifestMetadata)}); return;}
      if (record(value) && value.format === 'datapass.architecture') setPending({doc: {...validateArchitecture(value), origin: 'user-file'}});
      else if (record(value) && record(value.metadata) && /\/manifest\//.test(String(value.metadata.dbt_schema_version))) setPending({doc: fromDbtManifest(value), manifestMetadata: value.metadata});
      else setPending({doc: fromPipeline(parsePipeline(source))});
    } catch (e) {setError(e instanceof Error ? e.message : String(e));} finally {setBusy(false);}
  }
  function download(kind: 'json' | 'svg' | 'html') {
    const content = kind === 'json' ? JSON.stringify(exportArchitecture(doc, includeSource), null, 2) : kind === 'svg' ? architectureSvg(doc) : architectureReport(doc, includeSource);
    createBrowserHost().saveDownload(`architecture-review.${kind}`, new Blob([content], {type: kind === 'json' ? 'application/json' : kind === 'svg' ? 'image/svg+xml' : 'text/html'}));
  }
  const match = (n: ArchitectureNode) => `${n.label} ${n.layer} ${n.owner}`.toLowerCase().includes(query.toLowerCase());
  const focus = selected && direction !== 'all' ? new Set([selected, ...(direction === 'upstream' ? upstream : downstream)]) : null;
  const nodes: Node<DiagramData>[] = doc.nodes.map(n => ({id: n.id, type: 'architecture', position: positions.get(n.id)!, data: {item: n, mode, active: selected === n.id, dimmed: !match(n) || !!focus && !focus.has(n.id) || present && activeChapter.ids.length > 0 && !activeChapter.ids.includes(n.id)}, ariaLabel: n.label}));
  const edges = doc.edges.map(e => ({id: e.id, source: e.from, target: e.to, sourceHandle: positions.get(e.from)!.x === positions.get(e.to)!.x ? 'bottom' : 'right', targetHandle: positions.get(e.from)!.x === positions.get(e.to)!.x ? 'top' : 'left', type: 'smoothstep', label: e.label, animated: false, markerEnd: {type: MarkerType.ArrowClosed}, style: {stroke: selected && (e.from === selected || e.to === selected) ? '#28669a' : '#a4afbe', strokeWidth: 1.5, strokeDasharray: e.kind !== 'data' ? '5 4' : undefined}, labelStyle: {fontSize: 10, fill: '#58687a'}}));
  const visibleMatrix = doc.nodes.filter(match), maxMatrixPage = Math.max(0, Math.ceil(visibleMatrix.length / 24) - 1), matrix = visibleMatrix.slice(Math.min(matrixPage, maxMatrixPage) * 24, (Math.min(matrixPage, maxMatrixPage) + 1) * 24);
  return <section className={'architecture-panel' + (present ? ' presenting' : '')} aria-label="Architecture review workspace">
    <header className="arch-heading"><div><span className="arch-eyebrow">DataPass / IT architecture</span><h1>{doc.title}</h1><p>{present ? 'Architecture review - presentation view' : 'A web view over your architecture artifacts. No IDE, live connection or execution required.'}</p></div><div className="arch-actions">
      {!present && <><Button size="small" icon={<FileUp size={14}/>} disabled={busy} onClick={() => filePicker.current?.click()}>Import architecture</Button><Button size="small" disabled={busy || !doc.nodes.some(n => n.id.startsWith('model.') || n.id.startsWith('source.'))} onClick={() => catalogPicker.current?.click()}>Attach dbt catalog</Button></>}
      <Button size="small" icon={present ? <X size={14}/> : <Presentation size={14}/>} onClick={() => setPresent(v => !v)}>{present ? 'Exit presentation' : 'Present'}</Button>
      <details className="arch-export"><summary><Download size={14}/>Export</summary><div><p>Includes component names, owners, descriptions and schemas. Review before sharing.</p><label><input type="checkbox" checked={includeSource} onChange={e => setIncludeSource(e.target.checked)}/>Include source excerpts and paths (may contain secrets)</label><Button size="small" onClick={() => download('html')}>Download review HTML</Button><Button size="small" onClick={() => download('svg')}>Download diagram SVG</Button><Button size="small" onClick={() => download('json')}>Download architecture JSON</Button></div></details>
    </div></header>
    <div className="arch-evidence"><span className={'arch-badge ' + doc.origin}>{doc.origin === 'synthetic' ? 'Synthetic example' : 'User artifact - unverified'}</span><span>{doc.snapshot ? `${doc.snapshot.label}${doc.snapshot.generatedAt ? ' / ' + doc.snapshot.generatedAt : ''}` : 'No catalog snapshot supplied'}</span><span className="arch-session">Session only / export before reload</span></div>
    {error && <div className="arch-error" role="alert"><span>{error}</span><button type="button" aria-label="Dismiss architecture error" onClick={() => setError('')}><X size={14}/></button></div>}
    <div className="arch-facts"><span><b>{doc.nodes.length}</b> components</span><span><b>{doc.edges.length}</b> declared links</span><span><b>{facts.cycles.length}</b> cyclic groups</span><span><b>{facts.changes.length}</b> schema differences</span><span><b>{facts.compared}</b> comparable components</span><span className="arch-muted">{facts.reverseEdges.length} links oppose displayed layer order</span></div>
    {present ? <div className="arch-chapter" aria-live="polite"><div><span className="arch-eyebrow">{String(chapter + 1).padStart(2, '0')} / {chapters.length}</span><h2>{activeChapter.title}</h2><p>{activeChapter.body}</p></div><div><Button size="small" icon={<ArrowLeft size={14}/>} aria-label="Previous architecture chapter" disabled={chapter === 0} onClick={() => setChapter(c => c - 1)}/><Button size="small" icon={<ArrowRight size={14}/>} aria-label="Next architecture chapter" disabled={chapter === chapters.length - 1} onClick={() => setChapter(c => c + 1)}/></div></div> : <div className="arch-toolbar"><div role="tablist" aria-label="Architecture views">{(['map', 'drift', 'matrix'] as const).map(t => <button role="tab" aria-selected={tab === t} aria-controls={'arch-view-' + t} id={'arch-tab-' + t} key={t} onClick={() => setTab(t)}>{t === 'map' ? 'System map' : t === 'drift' ? 'Schema drift' : 'Dependencies'}</button>)}</div><label className="arch-search"><Search size={14}/><input aria-label="Find architecture component" placeholder="Find component, layer, owner" value={query} onChange={e => {setQuery(e.target.value); setMatrixPage(0);}}/></label><Button size="small" onClick={() => setPending({doc: demoArchitecture})}>Reset example</Button></div>}
    {(tab === 'map' || present) && <div className="arch-workspace" id="arch-view-map" role={present ? "region" : "tabpanel"} aria-label={present ? "Architecture map" : undefined} aria-labelledby={present ? undefined : "arch-tab-map"}>
      {!present && <nav className="arch-outline" aria-label="Architecture components">{doc.layers.map(layer => <section key={layer}><h3>{layer}</h3>{doc.nodes.filter(n => n.layer === layer && match(n)).map(n => <button type="button" key={n.id} aria-label={'Select ' + n.label} aria-pressed={selected === n.id} onClick={() => choose(n.id)}><Network size={13}/><span>{n.label}</span>{compareColumns(n).changes.length > 0 && <i/>}</button>)}</section>)}</nav>}
      <div className="arch-map"><div className="arch-map-tools"><label>Schema <select aria-label="Schema view" value={mode} onChange={e => setMode(e.target.value as typeof mode)}><option value="design">Declared design</option><option value="snapshot">Catalog snapshot</option></select></label>{!present && <label>Highlight <select aria-label="Dependency direction" value={direction} onChange={e => setDirection(e.target.value as typeof direction)}><option value="all">All components</option><option value="upstream">Upstream of selection</option><option value="downstream">Downstream of selection</option></select></label>}<button type="button" onClick={() => {setSelected(null); setQuery(''); setDirection('all');}}>Clear focus</button></div>
        <div className="arch-flow" data-testid="architecture-map"><ReactFlow key={generation} nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView fitViewOptions={{padding: .15, maxZoom: 1}} minZoom={.12} maxZoom={1.6} nodesDraggable={false} nodesConnectable={false} elementsSelectable onNodeClick={(_, n) => setSelected(n.id)}><Background gap={20} color="#dfe5ec"/><Controls showInteractive={false}/></ReactFlow></div><div className="arch-map-legend">Solid: data dependencies / Dashed: control or containment / Amber: schema differences. Definition only.</div>
      </div>
      {!present && <aside className="arch-inspector" aria-label="Selected architecture component">{node ? <><span className="arch-eyebrow">{node.layer} / {node.kind}</span><h2>{node.label}</h2><p>{node.description}</p><dl><dt>Owner</dt><dd>{node.owner || 'Not declared'}</dd><dt>Potential dependency reach</dt><dd>{upstream.size} upstream / {downstream.size} downstream</dd></dl><ColumnTable node={node}/><details className="arch-source"><summary>Source excerpt (read-only)</summary><p>{node.sourcePath || 'No relative source path supplied'}</p>{node.code ? <pre><code>{node.code}</code></pre> : <p>No source excerpt attached.</p>}<small>Displayed as text only. No query, script or notebook is executed.</small></details>{downstream.size > 0 && <div className="arch-neighbors"><h3>Downstream components</h3>{doc.nodes.filter(n => downstream.has(n.id)).map(n => <button key={n.id} onClick={() => choose(n.id)}>{n.label}<ArrowRight size={12}/></button>)}</div>}</> : <div className="arch-empty"><Network size={25}/><h2>Inspect a component</h2><p>Select a node to see its role, schema, source excerpt and downstream dependencies.</p><p>These are declared relationships, not observed production traffic.</p></div>}</aside>}
    </div>}
    {tab === 'drift' && !present && <section className="arch-analysis" id="arch-view-drift" role="tabpanel" aria-labelledby="arch-tab-drift"><h2>Declared design / catalog snapshot</h2><p>Exact-name comparison. Renames, type aliases and breaking-change severity are not inferred. A missing snapshot is not a successful comparison.</p><div className="arch-table-scroll"><table><thead><tr><th>Component</th><th>Column</th><th>Difference</th><th>Design</th><th>Snapshot</th></tr></thead><tbody>{facts.changes.map((c, i) => <tr key={i}><td><button onClick={() => choose(c.nodeId)}>{doc.nodes.find(n => n.id === c.nodeId)!.label}</button></td><td>{c.column}</td><td>{c.kind}</td><td>{c.design}</td><td>{c.snapshot}</td></tr>)}</tbody></table></div>{!facts.changes.length && <p>No differences in supplied comparisons. Inspect the coverage below.</p>}<p className="arch-muted">Coverage: {facts.compared}/{doc.nodes.length} components have both schemas. {doc.nodes.reduce((sum, n) => sum + compareColumns(n).unknown, 0)} type/nullability comparisons remain unknown.</p></section>}
    {tab === 'matrix' && !present && <section className="arch-analysis" id="arch-view-matrix" role="tabpanel" aria-labelledby="arch-tab-matrix"><h2>Dependency matrix</h2><p>Row supplies column. Direct data/control links only; containment is excluded. Click a filled cell to inspect its source.</p><div className="arch-matrix-nav"><span>{matrix.length} of {visibleMatrix.length} matching components / page {Math.min(matrixPage, maxMatrixPage) + 1} of {maxMatrixPage + 1}. Off-page links are not shown.</span><Button size="small" disabled={matrixPage <= 0} onClick={() => setMatrixPage(p => p - 1)}>Previous matrix page</Button><Button size="small" disabled={matrixPage >= maxMatrixPage} onClick={() => setMatrixPage(p => p + 1)}>Next matrix page</Button></div><div className="arch-table-scroll"><table className="arch-matrix"><caption className="arch-sr">Direct dependencies, row to column</caption><thead><tr><th>From / to</th>{matrix.map((n, i) => <th key={n.id} title={n.label}>{i + 1}</th>)}</tr></thead><tbody>{matrix.map((a, i) => <tr key={a.id}><th scope="row">{i + 1}. {a.label}</th>{matrix.map(b => {const e = doc.edges.find(e => e.kind !== 'contains' && e.from === a.id && e.to === b.id); return <td key={b.id}>{e ? <button aria-label={a.label + ' to ' + b.label} title={e.kind + ': ' + e.label} onClick={() => choose(a.id)}/> : <span aria-label="No direct link"/>}</td>;})}</tr>)}</tbody></table></div>{facts.cycles.length > 0 && <p className="arch-warning">Cyclic groups: {facts.cycles.map(g => g.map(id => doc.nodes.find(n => n.id === id)!.label).join(', ')).join('; ')}</p>}</section>}
    {!present && <details className="arch-scope"><summary>Scope, evidence and import formats</summary><p>Import DataPass architecture JSON, dbt manifest.json, or the existing DataPass / ADF / Fabric pipeline subset. Attach dbt catalog.json separately for schema comparison. Limit: 2 MiB, 180 components, 400 links.</p>{doc.notes.map((n, i) => <p key={i}>{n}</p>)}<p>The browser does not fetch source files, read a repository, run dbt, start Hop, or connect to your warehouse. JSON export is a Studio review artifact, not a DiagramCloud or Azure deployment contract.</p></details>}
    <input ref={filePicker} hidden type="file" accept=".json,application/json" aria-label="Import architecture file" onChange={e => void importFile(e, false)}/><input ref={catalogPicker} hidden type="file" accept=".json,application/json" aria-label="Import dbt catalog file" onChange={e => void importFile(e, true)}/>
    {pending && <ImportReview pending={pending} apply={applyImport} cancel={() => setPending(null)}/>}
  </section>;
}
