import {useMemo,useRef,useState} from 'react';
import {ReactFlow,Background,Controls,MiniMap,MarkerType,Handle,Position,type NodeProps,type Node,type Connection,type NodeChange} from '@xyflow/react';
import {Button,Input} from '../fluent';
import {Download,FileUp,Plus,Trash2,Code2,Database,Filter,CheckCircle2,Boxes,ChartNoAxesCombined} from 'lucide-react';
import {useRoomStore} from '../store';
import {demoPipeline,parsePipeline,pipelineIssues,type Activity} from '../core/pipeline';
import {createBrowserHost} from '../core/host';
import {Header} from './Common';
const icons={Source:Database,Filter,Check:CheckCircle2,Aggregate:ChartNoAxesCombined,Publish:Boxes};
type ActivityNode=Node<{activity:Activity;selected:boolean},'activity'>;
function ActivityCard({data}:NodeProps<ActivityNode>){const Icon=icons[data.activity.kind as keyof typeof icons]||Boxes;return <div className={'activity-node '+(data.selected?'active':'')}><Handle type="target" position={Position.Left}/><div className="activity-kind"><Icon size={16}/>{data.activity.kind}</div><strong>{data.activity.name}</strong><small>Definition only</small><Handle type="source" position={Position.Right}/></div>;}
const nodeTypes={activity:ActivityCard};
export default function PipelinePanel(){
 const pipeline=useRoomStore(s=>s.datapass.pipeline),setPipeline=useRoomStore(s=>s.datapass.setPipeline),setError=useRoomStore(s=>s.datapass.setError),open=useRoomStore(s=>s.datapass.openModule),ensure=useRoomStore(s=>s.sqlEditor.ensureQuery);
 const [selected,setSelected]=useState<string|undefined>(pipeline.activities[0]?.id),[inspector,setInspector]=useState<'properties'|'source'>('properties'),picker=useRef<HTMLInputElement>(null);
 const node=pipeline.activities.find(n=>n.id===selected),issues=useMemo(()=>pipelineIssues(pipeline),[pipeline]);
 const nodes=useMemo(()=>pipeline.activities.map(a=>({id:a.id,type:'activity' as const,position:{x:a.x,y:a.y},data:{activity:a,selected:a.id===selected}})),[pipeline,selected]);
 const edges=useMemo(()=>pipeline.dependencies.map(e=>({id:e.id,source:e.from,target:e.to,label:e.condition,type:'smoothstep',markerEnd:{type:MarkerType.ArrowClosed},style:{stroke:e.condition==='contains'?'#a4aab5':'#65887a'},labelStyle:{fill:'#616b78',fontSize:11}})),[pipeline]);
 function connect(c:Connection){if(!c.source||!c.target||c.source===c.target||pipeline.dependencies.length>=400||pipeline.dependencies.some(e=>e.from===c.source&&e.to===c.target))return;setPipeline({...pipeline,dependencies:[...pipeline.dependencies,{id:'edge_'+crypto.randomUUID(),from:c.source,to:c.target,condition:'Succeeded'}]});}
 function nodeChanges(changes:NodeChange<ActivityNode>[]){const positions=changes.filter((c):c is Extract<NodeChange<ActivityNode>,{type:'position'}>=>c.type==='position'&&c.position!==undefined);if(!positions.length)return;setPipeline({...pipeline,activities:pipeline.activities.map(a=>{const change=positions.find(c=>c.id===a.id);return change?.type==='position'&&change.position?{...a,x:Math.max(-50000,Math.min(50000,change.position.x)),y:Math.max(-50000,Math.min(50000,change.position.y))}:a;})});}
 function add(kind:string){const id='activity_'+crypto.randomUUID();setPipeline({...pipeline,activities:[...pipeline.activities,{id,kind,name:'New '+kind,detail:'Authored locally; no execution engine is attached.',sourcePath:'local-draft',code:'',x:80+(pipeline.activities.length%4)*250,y:400+Math.floor(pipeline.activities.length/4)*140}]});setSelected(id);}
 return <section className="pipeline-panel"><Header eyebrow="Author / pipeline definitions" title={pipeline.title} detail="An ADF-style authoring surface. Inspect and arrange dependencies without pretending to run a cloud orchestrator."><Button size="small" icon={<FileUp size={14}/>} onClick={()=>picker.current?.click()}>Import JSON</Button><Button size="small" icon={<Download size={14}/>} onClick={()=>createBrowserHost().saveDownload('pipeline.studio.json',new Blob([JSON.stringify(pipeline,null,2)],{type:'application/json'}))}>Export draft</Button></Header>
 <input hidden type="file" ref={picker} accept=".json" aria-label="Import pipeline definition" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>2*1024*1024)throw new Error('Maximum pipeline size: 2 MiB');const p=parsePipeline(await file.text());setPipeline(p);setSelected(p.activities[0]?.id);}catch(error){setError(String(error));}}}/>
 <div className="pipeline-toolbar"><span className="eyebrow">Activities</span>{['Source','Filter','Aggregate','Check','Publish'].map(kind=><Button key={kind} disabled={pipeline.activities.length>=180} size="small" appearance="subtle" icon={<Plus size={12}/>} onClick={()=>add(kind)}>{kind}</Button>)}<span className="spacer"/><span className={'pill '+(issues.length?'warning':'')}>{issues.length?`${issues.length} graph issues`:'DAG structure valid'}</span></div>
 <div className="pipeline-layout"><div className="pipeline-canvas"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_,n)=>setSelected(n.id)} onNodesChange={nodeChanges} onConnect={connect} fitView minZoom={.25} maxZoom={1.5} nodesDraggable elementsSelectable deleteKeyCode={null}><Background gap={20} size={1}/><Controls showInteractive={false}/><MiniMap nodeColor="#d4dedb"/></ReactFlow></div><aside className="activity-inspector"><div className="inspector-tabs"><button onClick={()=>setInspector('properties')} className={inspector==='properties'?'active':''}>Properties</button><button onClick={()=>setInspector('source')} className={inspector==='source'?'active':''}>Source / code</button></div>{node?<><span className="eyebrow">{node.kind}</span><h2>{node.name}</h2>{inspector==='properties'?<><label>Name<Input value={node.name} onChange={(_,d)=>setPipeline({...pipeline,activities:pipeline.activities.map(a=>a.id===node.id?{...a,name:d.value.slice(0,200)}:a)})}/></label><p>{node.detail}</p><h3>Source location</h3><code className="source-path">{node.sourcePath}</code><h3>Incoming / outgoing</h3>{pipeline.dependencies.filter(e=>e.from===node.id||e.to===node.id).map(e=><div className="dependency-row" key={e.id}><span>{pipeline.activities.find(a=>a.id===(e.from===node.id?e.to:e.from))?.name}<small>{e.condition}</small></span><Button size="small" appearance="subtle" icon={<Trash2 size={13}/>} aria-label={'Remove dependency '+e.id} onClick={()=>setPipeline({...pipeline,dependencies:pipeline.dependencies.filter(x=>x.id!==e.id)})}/></div>)}<Button size="small" icon={<Trash2 size={13}/>} disabled={pipeline.activities.length<=1} onClick={()=>{setPipeline({...pipeline,activities:pipeline.activities.filter(a=>a.id!==node.id),dependencies:pipeline.dependencies.filter(e=>e.from!==node.id&&e.to!==node.id)});setSelected(undefined);}}>Remove activity</Button></>:<><pre className="source-code">{node.code||'No executable source. This is an authored visual activity.'}</pre>{pipeline.sourceKind==='synthetic'&&/^SELECT/i.test(node.code)&&<Button size="small" icon={<Code2 size={14}/>} onClick={()=>{ensure('pipeline-'+node.id,{name:node.name,query:node.code,open:true,select:true});open('sql');}}>Review query in SQL</Button>}<p className="footnote">Source text is displayed, never executed by this canvas. Open a demo query in SQL to run it explicitly.</p></>}</>:<p>Select an activity.</p>}</aside></div>
 <div className="pipeline-status"><span>{pipeline.activities.length} activities &middot; {pipeline.dependencies.length} dependencies &middot; {pipeline.sourceKind}</span><span className="spacer"/><Button size="small" appearance="subtle" onClick={()=>{setPipeline(structuredClone(demoPipeline));setSelected('landing');}}>Restore demo</Button></div>{issues.length>0&&<div className="notice warning" role="status">{issues.join(' ')}</div>}
 </section>;
}
