import assert from 'node:assert/strict';
import {readFile,writeFile,lstat} from 'node:fs/promises';
import path from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {SiteRuntime} from '../../src/framework/runtime.ts';
import {loadClient} from '../../scripts/load-client.mjs';
import {captureBuiltClient,parseCaptureArguments} from '../../scripts/capture-client.mjs';

export async function testCapture({served,step,expect,id,snapshot,output,report,sha}){
    const contentRuntime=new SiteRuntime(await loadClient(id('content'))),target=contentRuntime.save('overview');Object.assign(target.values,{'custom-selection':'alpha','custom-representation':'canvas','custom-show-alpha':false});const stateFile=path.join(output,'content-target.json');await writeFile(stateFile,JSON.stringify(target)+'\n');
    const captureOptions=(client,name,state,flags=[])=>parseCaptureArguments([client,'--out',path.join(output,name),'--state',state,'--port','4179',...flags]);
    await step('target-state captures round-trip and repeat byte-identically in one environment',async()=>{const first=await captureBuiltClient(captureOptions(id('content'),'capture-a',stateFile)),second=await captureBuiltClient(captureOptions(id('content'),'capture-b',stateFile));assert.equal(first.screenshot.sha256,second.screenshot.sha256);assert.ok(first.screenshot.bytes>5000);assert.equal(first.source.headSha,report.sourceSha);assert.equal(first.build.containsThree,false);assert.equal(first.state.roundTripVerified,true);report.captures.push({kind:'content-twice',sha256:first.screenshot.sha256,sourceDirty:first.source.workingTreeDirty,byteIdentical:true});});
    // The default 1000px frame showed only the guide; include the native 3D surface.
    await step('capture includes the existing GLB renderer and explicit saved model state',async()=>{const state=new SiteRuntime(await loadClient(id('model'))).save('overview');Object.assign(state.values,{'model-selection':'plate','model-camera':'plate','model-mode':'assembled','model-view':'model','engine-step':1});const file=path.join(output,'model-target.json');await writeFile(file,JSON.stringify(state)+'\n');const metadata=await captureBuiltClient(captureOptions(id('model'),'capture-model',file,['--height','2160']));assert.equal(metadata.viewport.height,2160);assert.ok(metadata.requests.some(request=>request.path.endsWith('.glb')));assert.equal(metadata.state.roundTripVerified,true);report.captures.push({kind:'model',sha256:metadata.screenshot.sha256});});
    await step('capture freezes a supplied missing replay sample rather than fabricating values',async()=>{const state=new SiteRuntime(await loadClient(id('replay'))).save('overview');Object.assign(state.values,{'replay-selection':'unit-b','replay-frame':2});const file=path.join(output,'replay-target.json');await writeFile(file,JSON.stringify(state)+'\n');const metadata=await captureBuiltClient(captureOptions(id('replay'),'capture-replay',file));assert.equal(metadata.state.roundTripVerified,true);assert.equal(metadata.build.containsThree,false);report.captures.push({kind:'replay-null',sha256:metadata.screenshot.sha256});});
    await step('capture preflight refuses overwrite and invalid saved semantic IDs',async()=>{const before=sha(await readFile(path.join(output,'capture-a','capture.png')));await assert.rejects(()=>captureBuiltClient(captureOptions(id('content'),'capture-a',stateFile)),/EEXIST/);assert.equal(sha(await readFile(path.join(output,'capture-a','capture.png'))),before);const invalid=structuredClone(target);invalid.values['custom-selection']='not-an-entity';const file=path.join(output,'invalid-state.json');await writeFile(file,JSON.stringify(invalid));await assert.rejects(()=>captureBuiltClient(captureOptions(id('content'),'capture-invalid',file)));await assert.rejects(()=>lstat(path.join(output,'capture-invalid')),{code:'ENOENT'});});
    await step('capture rejects visible error markers and broken images without a success receipt',async()=>{const file='dist-clients/'+id('content')+'/index.html',html=await readFile(file,'utf8');try{for(const [name,markup]of [['error','<p data-capture-state="error">Unrenderable fixture</p>'],['image','<img src="/missing-capture-proof.png" alt="Missing fixture">']]){await writeFile(file,html.replace('</body>',markup+'</body>'));await assert.rejects(()=>captureBuiltClient(captureOptions(id('content'),'capture-failed-'+name,stateFile)));await assert.rejects(()=>lstat(path.join(output,'capture-failed-'+name,'metadata.json')),{code:'ENOENT'});assert.equal(JSON.parse(await readFile(path.join(output,'capture-failed-'+name,'failure.json'),'utf8')).status,'failed');}}finally{await writeFile(file,html);}});
}
