import assert from 'node:assert/strict';

export async function testContent({served,step,expect,id,snapshot,output,report,sha}){
    await served(id('content'),async({page,requests})=>{
      await step('SVG keyboard selection, Canvas picking and inspector share one semantic ID',async()=>{await page.getByRole('button',{name:'Select Alpha in SVG',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('[data-context-id=alpha]')).toBeVisible();await page.getByRole('button',{name:'Canvas view',exact:true}).click();await expect(page.locator('canvas')).toHaveAttribute('aria-label',/selected alpha/);const box=await page.locator('canvas').boundingBox(),scale=Math.min(box.width/600,box.height/250);await page.mouse.click(box.x+(box.width-600*scale)/2+420*scale,box.y+(box.height-250*scale)/2+110*scale);await expect(page.locator('[data-context-id=beta]')).toBeVisible();await page.locator('[data-context-id=beta]').getByRole('button',{name:'Alpha',exact:true}).click();await expect(page.locator('[data-context-id=alpha]')).toBeVisible();});
      await step('hiding a selected projection does not erase the semantic identity',async()=>{await page.getByRole('button',{name:'Hide Alpha',exact:true}).click();await expect(page.getByRole('status')).toContainText('identity is retained');await expect(page.locator('[data-context-id=alpha]')).toBeVisible();await page.getByRole('button',{name:'SVG view',exact:true}).click();await expect(page.getByRole('button',{name:'Select Alpha in SVG',exact:true})).toHaveCount(0);await snapshot(page,'custom-hidden-selection');});
      await step('custom container observes resize and remains usable at 320 pixels',async()=>{await page.setViewportSize({width:320,height:760});await expect(page.locator('[data-capture-state]')).toHaveAttribute('data-capture-state','ready');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow at 320px');await expect.poll(async()=>Number((await page.locator('[data-visual-size]').getAttribute('data-visual-size')).split('x')[0])).toBeLessThan(320);await expect.poll(async()=>Number((await page.locator('[data-visual-size]').getAttribute('data-visual-size')).split('x')[0])).toBeGreaterThan(0);await snapshot(page,'custom-320px');});
      await step('repeated custom unmounts disconnect the owned ResizeObserver',async()=>{for(let i=0;i<4;i++){await page.getByRole('navigation',{name:'Site pages'}).getByRole('button',{name:'Other page',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Reflect.get(window,'__engineOwnedObservers').size)).toBe(0);await page.getByRole('navigation',{name:'Site pages'}).getByRole('button',{name:'Overview',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Reflect.get(window,'__engineOwnedObservers').size)).toBe(1);}await expect(page.locator('[data-context-id=alpha]')).toBeVisible();assert.ok(!requests.some(url=>/SceneViewport|ModelViewport|Architecture-|\.wasm|duckdb/.test(url)));});
    },{instrument:true});
    await served(id('content'),async({page})=>{await step('Canvas failure stays explicit and the SVG alternative remains usable',async()=>{await page.getByRole('button',{name:'Canvas view',exact:true}).click();await expect(page.locator('[data-custom-visual]')).toHaveAttribute('data-capture-state','error');await expect(page.getByRole('alert')).toContainText('Canvas is unavailable');await page.getByRole('button',{name:'SVG view',exact:true}).click();await expect(page.locator('[data-custom-visual]')).toHaveAttribute('data-capture-state','ready');await snapshot(page,'custom-canvas-fallback');});},{canvasFailure:true});
}
