import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';

export async function testModel({served,step,expect,id,snapshot,output,report,sha}){
    await served(id('model'),async({page,requests})=>{
      let identity;
      await step('a custom D3 plan consumes the original StoryPlayer without eager GLB',async()=>{await expect(page.getByTestId('model-plan')).toHaveAttribute('data-story-index','0');assert.ok(!requests.some(url=>/\.glb|ModelViewport-/.test(url)));await page.getByRole('button',{name:'Evaluate once',exact:true}).click();await expect(page.getByTestId('execution-witness')).toHaveAttribute('data-runs','1');identity=await page.getByTestId('execution-witness').getAttribute('data-result-identity');await page.getByRole('button',{name:'Next shared scene',exact:true}).click();await expect(page.getByTestId('model-plan')).toHaveAttribute('data-selection','plate');await expect(page.getByTestId('model-workbench')).toHaveAttribute('data-selection','plate');});
      await step('automatic story progression does not pause on its own atomic cue',async()=>{await page.getByRole('button',{name:'Previous shared scene',exact:true}).click();await page.getByRole('button',{name:'Play story',exact:true}).click();await expect(page.getByTestId('model-plan')).toHaveAttribute('data-story-index','2');});
      await step('manual native model selection yields the existing story clock',async()=>{await page.getByRole('button',{name:'Previous shared scene',exact:true}).click();await page.getByRole('button',{name:'Previous shared scene',exact:true}).click();await page.getByRole('button',{name:'Play story',exact:true}).click();await expect(page.getByTestId('model-plan')).toHaveAttribute('data-story-index','1');await page.getByRole('button',{name:'Inspect Carriage',exact:true}).click();await expect(page.getByRole('button',{name:'Play story',exact:true})).toBeVisible();const index=await page.getByTestId('model-plan').getAttribute('data-story-index');await delay(1100);await expect(page.getByTestId('model-plan')).toHaveAttribute('data-story-index',index);await expect(page.getByTestId('model-plan')).toHaveAttribute('data-selection','carriage');});
      await step('same part identity survives hidden plan, 3D, camera and model modes',async()=>{await page.getByRole('button',{name:'Plan select Oscillating plate',exact:true}).click();await page.getByRole('button',{name:'Hide plate in plan',exact:true}).click();await expect(page.getByTestId('model-plan')).toHaveAttribute('data-selection','plate');await page.getByRole('button',{name:'Load verified 3D model',exact:true}).click();await expect(page.getByText('3D ready',{exact:true})).toBeVisible();await expect(page.locator('.studio-scene-viewport')).toHaveAttribute('data-selection','plate');for(const mode of ['exploded','wireframe','assembled'])await page.getByLabel('Model mode',{exact:true}).selectOption(mode);await page.getByLabel('Model camera',{exact:true}).selectOption('side');await expect(page.locator('canvas[data-renderer=three-webgl2]')).toHaveAttribute('data-animating','false');await page.getByRole('button',{name:'Inspect Conversion module',exact:true}).click();await expect(page.getByTestId('model-plan')).toHaveAttribute('data-selection','module');await expect(page.getByTestId('execution-witness')).toHaveAttribute('data-runs','1');await expect(page.getByTestId('execution-witness')).toHaveAttribute('data-result-identity',identity);await snapshot(page,'model-shared-identity');});
      await step('native scroll selects authored story stops and direct interaction pauses it',async()=>{await page.getByRole('button',{name:'Enable scroll steps',exact:true}).click();await expect(page.getByTestId('model-plan')).toHaveAttribute('data-following','true');await page.getByTestId('scroll-track').evaluate(element=>{const rect=element.getBoundingClientRect();window.scrollTo(0,scrollY+rect.top-16+(rect.height-250)*.96);});await expect(page.getByTestId('model-plan')).toHaveAttribute('data-story-index','2');await page.getByRole('button',{name:'Inspect Carriage',exact:true}).click();await expect(page.getByTestId('model-plan')).toHaveAttribute('data-following','false');await expect(page.getByTestId('model-workbench')).toHaveAttribute('data-selection','carriage');await page.getByRole('button',{name:'Use direct controls',exact:true}).click();await expect(page.getByTestId('execution-witness')).toHaveAttribute('data-runs','1');});
      await step('reduced motion disables automatic guides but preserves manual story steps',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await expect(page.getByRole('button',{name:'Enable scroll steps',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Play story',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Previous shared scene',exact:true}).click();await expect(page.getByTestId('model-plan')).toHaveAttribute('data-story-index','1');});
    },{reduced:'no-preference'});
}
