/** Galaxy Navigator registry snapshot.
 * Reads the canonical App Galaxy registry (galaxy.json, kept by Claude Control) and writes a
 * minimised, public-safe subset to ../registry.generated.ts. Only IDs, names, stacks, repo slugs,
 * statuses and relations are kept. Local paths, notes, "where" pointers, entry points and free-text
 * descriptions are dropped on purpose.
 *
 * Usage (repo root):
 *   node clients/galaxy-navigator/tools/registry.mjs [path/to/galaxy.json]
 *   node clients/galaxy-navigator/tools/registry.mjs --check   (validates the committed snapshot only)
 * Default source: $GALAXY_JSON, else ~/.claude/effort-board/galaxy.json.
 */
import {readFile,writeFile} from 'node:fs/promises';
import {homedir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const out=path.join(here,'..','registry.generated.ts');
const STATUSES=['live','branch','planned','proposed','no-consumer','retired'];
const ID=/^[a-z][a-z0-9._/-]{0,79}$/;
/** Strings that must never reach a public bundle. */
const FORBIDDEN=[/[A-Za-z]:\\/,/\\Users\\/i,/\/Users\//,/@[a-z0-9-]+\.[a-z]{2,}/i,/\b(token|password|apikey|api_key)\s*[:=]/i];

export function assertPublicSafe(value,where='registry'){
  const text=JSON.stringify(value);
  for(const re of FORBIDDEN)if(re.test(text))throw new Error(`${where}: forbidden content matches ${re}`);
}
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
const slug=repo=>{const first=clean(repo).split(' ')[0]||'';return first.includes('/')?first.split('/').pop():first;};

/** galaxy.json -> minimised registry. Pure; throws on unknown status or malformed IDs. */
export function minimise(galaxy){
  if(!galaxy||!Array.isArray(galaxy.apps)||!Array.isArray(galaxy.contracts))throw new Error('Not a galaxy.json registry');
  const nodes=new Map();
  for(const a of galaxy.apps){
    if(!ID.test(a.id))throw new Error('Bad app id '+a.id);
    nodes.set(a.id,{id:a.id,name:clean(a.name),kind:'app',stack:clean(a.stack),repo:a.repo?slug(a.repo):'',hub:!!a.hub});
  }
  const ensure=id=>{if(!ID.test(id))throw new Error('Bad node id '+id);if(!nodes.has(id))nodes.set(id,{id,name:id,kind:'repo',stack:'',repo:id,hub:false});};
  const contracts=[];
  for(const c of galaxy.contracts){
    if(!STATUSES.includes(c.status))throw new Error('Unknown status '+c.status+' on '+c.id);
    ensure(c.ownerApp);for(const x of c.consumers||[])ensure(x);
    contracts.push({id:clean(c.id),name:clean(c.name),owner:c.ownerApp,consumers:[...(c.consumers||[])],status:c.status});
  }
  const byId=new Map(contracts.map(c=>[c.id,c]));
  const edges=new Map();
  const add=(from,to,contract,kind,status)=>{const id=`${from}>${to}:${contract}`;if(!edges.has(id))edges.set(id,{id,from,to,contract,kind,status});};
  for(const c of contracts)for(const to of c.consumers)add(c.owner,to,c.id,'',c.status);
  for(const x of galaxy.connections||[]){
    ensure(x.from);ensure(x.to);
    const status=STATUSES.includes(x.status)?x.status:(byId.get(x.contract)?.status||'planned');
    const id=`${x.from}>${x.to}:${x.contract}`;
    if(edges.has(id))edges.get(id).kind=clean(x.kind);else add(x.from,x.to,clean(x.contract),clean(x.kind),status);
  }
  const registry={format:'galaxy-navigator.registry',version:1,
    source:{name:'galaxy.json (App Galaxy registry)',generated:clean(galaxy.generated),updated:clean(galaxy.updated||galaxy.generated)},
    nodes:[...nodes.values()].sort((a,b)=>a.id.localeCompare(b.id)),
    contracts:contracts.sort((a,b)=>a.id.localeCompare(b.id)),
    edges:[...edges.values()].sort((a,b)=>a.id.localeCompare(b.id))};
  assertPublicSafe(registry);
  return registry;
}

if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
  if(process.argv.includes('--check')){
    const text=await readFile(out,'utf8');
    for(const re of FORBIDDEN)if(re.test(text))throw new Error('registry.generated.ts: forbidden content matches '+re);
    console.log('Galaxy registry snapshot OK');
  }else{
    const src=process.argv[2]||process.env.GALAXY_JSON||path.join(homedir(),'.claude','effort-board','galaxy.json');
    const registry=minimise(JSON.parse(await readFile(src,'utf8')));
    const body=`/** GENERATED by tools/registry.mjs from the App Galaxy registry (galaxy.json). Do not edit.\n * Public-safe subset: IDs, names, stacks, repo slugs, statuses and relations only. */\nimport type {Registry} from './registry.ts';\nexport const REGISTRY:Registry=${JSON.stringify(registry,null,1)};\n`;
    await writeFile(out,body);
    console.log(`Wrote ${path.relative(process.cwd(),out)}: ${registry.nodes.length} nodes, ${registry.contracts.length} contracts, ${registry.edges.length} edges`);
  }
}
