import {readPublication} from './publication.mjs';
import {spawnSync} from 'node:child_process';
import {existsSync,lstatSync} from 'node:fs';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {planCapabilities} from '../src/framework/capabilities.ts';
import {loadClient} from './load-client.mjs';
const id=process.argv[2];
if(!id||!/^[a-z][a-z0-9-]{0,59}$/.test(id)||process.argv.length!==3)throw new Error('Usage: npm run build:client -- <client-id>');
const dir=path.resolve('clients',id);if(!existsSync(path.join(dir,'app.ts'))||lstatSync(dir).isSymbolicLink())throw new Error('Unknown or symbolic client directory');
const bootstrap=spawnSync(process.execPath,['scripts/bootstrap-upstreams.mjs'],{stdio:'inherit',env:process.env});
if(bootstrap.status!==0)process.exit(bootstrap.status||1);
const definition=await loadClient(id);
const publication=await readPublication(dir,{title:definition.manifest.title,description:definition.manifest.description||'A DataPass client application.'});
const plan=planCapabilities(definition);
for(const warning of plan.warnings)console.warn(warning);
const run=(args)=>{const p=spawnSync(process.execPath,args,{stdio:'inherit',env:{...process.env,STUDIO_CLIENT:id,STUDIO_PUBLICATION:JSON.stringify(publication),STUDIO_CAPABILITIES:JSON.stringify(plan.capabilities),STUDIO_TITLE:definition.manifest.title,STUDIO_DESCRIPTION:definition.manifest.description}});if(p.status!==0)process.exit(p.status||1);};
run(['scripts/prepare-fluent-icons.mjs']);
run(['--experimental-strip-types','scripts/check-clients.mjs',id]);
await mkdir('.generated',{recursive:true});
await writeFile('.generated/client-plan-'+id+'.json',JSON.stringify(plan,null,2)+'\n');
const tsconfig='.generated/tsconfig-client-'+id+'.json';
await writeFile(tsconfig,JSON.stringify({extends:'../tsconfig.json',include:['../clients/'+id,'../src/client-main.tsx','../src/framework','../src/dom-compat.d.ts','../vite.client.config.ts']},null,2));
run(['node_modules/typescript/bin/tsc','--noEmit','-p',tsconfig]);
run(['node_modules/vite/bin/vite.js','build','--config','vite.client.config.ts']);
console.log(`Client ${id} built to dist-clients/${id}. No deployment was performed.`);
