import {build} from 'esbuild';
import {mkdir,readdir} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const ids=(await readdir('clients',{withFileTypes:true})).filter(d=>d.isDirectory()&&/^[a-z][a-z0-9-]{0,59}$/.test(d.name)).map(d=>d.name);
const imports=ids.map((id,i)=>`import app${i} from './clients/${id}/app.ts';`).join('\n');
const source=`import {compileLoopFrame} from './.upstream/conceptmotion/project/conceptmotion_studio/packages/core/src/algorithm.ts';\n${imports}\nimport {SiteRuntime} from './src/framework/runtime.ts';\nimport {chartInput} from './src/framework/chart-input.ts';\nimport {parseStory,parseVisualization} from './.upstream/vizforge/src/core/spec.ts';\nfor(const app of [${ids.map((_,i)=>'app'+i).join(',')}]){const runtime=new SiteRuntime(app);for(const e of Object.values(app.resources?.explanations||{}))e.spec.frames.forEach((_,i)=>compileLoopFrame(e.spec,i));for(const story of Object.values(app.resources?.stories||{}))parseStory(story.spec);for(const b of app.manifest.pages.flatMap(p=>p.sections.flatMap(s=>s.blocks))){if(b.type==='chart'){const d=app.manifest.datasets.find(d=>d.id===b.dataset);const value=chartInput(b,d,runtime.dataset(d.id));if(value.note)throw new Error(value.note);if(value.input)parseVisualization(value.input);}}console.log('Original VizForge / ConceptMotion contracts OK: '+app.manifest.id);}`;
await mkdir('.generated',{recursive:true});
const file=path.resolve('.generated/visual-contract-check.mjs');
await build({stdin:{contents:source,resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',packages:'external',outfile:file,jsx:'automatic',define:{__STUDIO_CHARTS__:'false',__STUDIO_3D__:'false',__STUDIO_STORIES__:'false',__STUDIO_ARCHITECTURE__:'false',__STUDIO_EXPLORER__:'false',__STUDIO_EXPLANATIONS__:'false'},logLevel:'warning'});
await import(pathToFileURL(file).href+'?run='+Date.now());
