import {motionStepEvidence} from './model.ts';
import {motionFrame, type CompiledMotion} from './compile.ts';
import {drawing, motionBounds, boundsText, pathData, polygonData, shade, statusColor} from './geometry.ts';
import type {MotionProjection} from './model.ts';
import {excerpt} from '../evidence/model.ts';

export const escapeMarkup = (value: unknown): string => String(value).replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]!));
/** Same canonical geometry as the live renderer. Exports the target snapshot, never a half-transition. */
export function motionSvg(compiled: CompiledMotion, index: number, mode: MotionProjection, selection = 'none'): string {
  const frame = motionFrame(compiled, index), scene = drawing(compiled, frame, mode), b = motionBounds(compiled, mode);
  const objects = scene.objects.filter(o => o.alpha > 0).map(o => `<g data-entity="${escapeMarkup(o.id)}"><title>${escapeMarkup(o.label)}</title>${o.faces.map((face, i) => `<polygon points="${polygonData(face)}" fill="${shade(o.color, i === 0 && mode === 'isometric' ? -.24 : i === 1 ? -.12 : .6)}" stroke="${o.id === selection ? '#124b6c' : shade(o.color, -.2)}" stroke-width="${o.id === selection ? 2.6 : 1.2}"/>`).join('')}<path d="${pathData(o.leader)}" fill="none" stroke="#93a8b8" stroke-width=".8" stroke-dasharray="2 3"/><circle cx="${o.center[0]}" cy="${Math.min(...o.faces.flat().map(p => p[1])) - 9}" r="${o.kind === 'station' ? 3 : 0}" fill="${statusColor(o.status)}"/>${o.labelLines.map((line, i) => `<text x="${o.labelPosition[0]}" y="${o.labelPosition[1] + i * 15}" text-anchor="middle" font-size="${o.kind === 'station' ? 12 : 10}" fill="#21384a" font-family="system-ui,sans-serif">${escapeMarkup(line)}</text>`).join('')}</g>`).join('');
  const annotations = scene.annotations.filter(a => a.alpha > 0).map(a => {
    const {x, y, width, height} = a.box;
    return `<g data-annotation="${escapeMarkup(a.id)}" data-anchor="${escapeMarkup(a.entity)}"><title>${escapeMarkup(a.text)}</title><path d="${pathData([a.anchor, [x + width / 2, y + height]])}" fill="none" stroke="#657f90" stroke-dasharray="3 3"/><rect x="${x}" y="${y}" width="${width}" height="${height}" rx="5" fill="#ffffff" stroke="#819aaa"/>${a.lines.map((line, i) => `<text x="${x + 11}" y="${y + 21 + i * 15}" font-family="system-ui,sans-serif" font-size="11" fill="#21384a">${escapeMarkup(line)}</text>`).join('')}</g>`;
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${boundsText({...b, height: b.height + 36})}" role="img"><title>${escapeMarkup(compiled.spec.title)} / ${escapeMarkup(compiled.spec.steps[index].title)}</title><desc>${compiled.spec.provenance === 'recorded' ? 'Snapshot of a recorded trace; layout and timing are presentation.' : 'Authored ' + escapeMarkup(compiled.spec.provenance) + ' snapshot, not an execution trace.'} ${escapeMarkup(compiled.spec.steps[index].caption)}</desc><rect x="${b.x}" y="${b.y}" width="${b.width}" height="${b.height + 36}" fill="#f7fafc"/><defs><marker id="motion-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10z" fill="#578ba4"/></marker></defs>${scene.links.map(link => `<path d="${pathData(link.path)}" fill="none" stroke="${link.active ? '#3284a4' : '#b4c5d0'}" stroke-width="${link.active ? 2.5 : 1.4}" marker-end="url(#motion-arrow)"/>`).join('')}${objects}${annotations}<text x="${b.x + 16}" y="${b.y + b.height + 17}" font-size="10" font-family="system-ui,sans-serif" fill="#647889">${escapeMarkup(compiled.spec.provenance.toUpperCase())} / ${index + 1} of ${compiled.frames.length} / ${escapeMarkup(mode)} / target snapshot</text></svg>`;
}
export function motionReport(compiled: CompiledMotion, index: number, mode: MotionProjection, includeSource = false): string {
  if (typeof includeSource !== 'boolean') throw new Error('Source export requires an explicit boolean');
  const spec = compiled.spec;
  const steps = spec.steps.map(step => `<li><h2>${escapeMarkup(step.title)}</h2><p>${escapeMarkup(step.caption)}</p>${(step.annotations || []).map(a => `<p><strong>${escapeMarkup(spec.entities.find(e => e.id === a.entity)!.label)}:</strong> ${escapeMarkup(a.text)}</p>`).join('')}${includeSource ? motionStepEvidence(step).map(ref => `<details><summary>${escapeMarkup(ref.label)} / ${escapeMarkup(spec.sources.find(s => s.id === ref.artifact)!.path)}:${ref.start}-${ref.end}</summary><pre>${escapeMarkup(excerpt(spec.sources, ref))}</pre></details>`).join('') : ''}</li>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"><title>${escapeMarkup(spec.title)}</title><style>body{font:15px/1.7 system-ui,sans-serif;color:#21384a;max-width:1040px;margin:40px auto;padding:0 24px}h1{font-size:32px;line-height:1.2}h2{font-size:19px}svg{width:100%;height:auto;border:1px solid #d7e2ea;border-radius:8px}li{padding:10px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f3f7fa;padding:15px}small,footer{color:#617487}summary{cursor:pointer}footer{border-top:1px solid #d7e2ea;padding-top:16px}</style></head><body><small>${escapeMarkup(spec.provenance)} / ${spec.provenance === 'recorded' ? 'recorded trace, authored presentation' : 'authored explanation'}</small><h1>${escapeMarkup(spec.title)}</h1><p>${escapeMarkup(spec.description)}</p>${motionSvg(compiled, index, mode)}<p>${escapeMarkup(spec.note)}</p><ol>${steps}</ol><footer>Source excerpts ${includeSource ? 'included by explicit choice' : 'omitted'}. Labels, narrative and visible relationships are included; review before sharing. This report does not prove code execution or model correctness.</footer></body></html>`;
}
