import type {ExplorerSpec,ExplorerItem,ExplorerDocument} from '../../src/framework/index.ts';
export const domains=[
  {id:'cloud',label:'Cloud platform',group:'platform',child:'pipeline',project:'Ingestion project',kind:'Pipeline',x:-4.6,z:-4.2,color:'#3d97c6',tags:['Ingestion','Contracts','Storage'],summary:'From a source contract to curated data.'},
  {id:'insights',label:'Business intelligence',group:'analytics',child:'reporting',project:'Reporting project',kind:'Analytics',x:4.6,z:-4.2,color:'#9878c7',tags:['Metrics','Semantic models','Decisions'],summary:'Make analytical definitions visible and reusable.'},
  {id:'models',label:'Data models',group:'modeling',child:'quality',project:'Quality project',kind:'Transformation',x:-4.6,z:4.2,color:'#55a88f',tags:['Quality','Determinism','Validation'],summary:'Explain how raw observations become trusted outputs.'},
  {id:'automation',label:'Automation',group:'delivery',child:'delivery',project:'Delivery project',kind:'Workflow',x:4.6,z:4.2,color:'#c19a58',tags:['Tasks','Release checks','Evidence'],summary:'An explicit path from input to a reviewed result.'}
];
const items:ExplorerItem[]=domains.flatMap((d,index)=>[
  {id:d.id,label:d.label,kind:'Capability',parent:null,group:d.group,summary:d.summary,description:'A synthetic capability block. Explore its project, switch information facets, and open the authored evidence without losing your place in the system.',tags:d.tags,position:[index*235,0],facts:[{label:'Scope',value:'Framework acceptance example'},{label:'Children',value:'1 authored project'}],scene:{entity:d.id,camera:d.id+'-front',facetCameras:{projects:d.id+'-side'}}},
  {id:d.child,label:d.project,kind:d.kind,parent:d.id,group:d.group,summary:'One authored example, not an employer claim.',description:d.summary+' This project is deliberately synthetic: the diagrams and code illustrate a method, not an audited production system.',tags:d.tags.slice(0,2),position:[index*235,240],facts:[{label:'Status',value:'Illustrative'},{label:'Evidence',value:'Authored, not measured'}],scene:{entity:d.child,camera:d.id+'-front',facetCameras:{projects:d.id+'-side'}},open:{page:['cloud','automation'].includes(d.id)?'implementation':'method',label:['cloud','automation'].includes(d.id)?'Open architecture walkthrough':'Open transformation explanation'}}
]);
const documents:ExplorerDocument[]=domains.flatMap(d=>[
  {id:d.id+'-skills',item:d.id,facet:'skills',title:d.label+' / building blocks',summary:d.summary,provenance:'synthetic' as const,source:'Synthetic reference content authored for Studio acceptance',sections:[{title:'What this capability contains',text:d.tags.join(', ')+'. The framework does not turn these tags into a proficiency score or certification.'},{title:'Explore, then inspect',text:'Select the project beneath this capability. Facets change the information shown, while Map and Library keep the same selected component.'}]},
  {id:d.child+'-case',item:d.child,facet:'projects',title:d.project+' / approach',summary:'Purpose, boundaries and a declared implementation path.',provenance:'synthetic' as const,source:'Authored reference, no customer documents',sections:[{title:'Problem and scope',text:d.summary},{title:'A bounded implementation',text:'Keep the source contract, transformation and presentation separate. A chart selection is not an instruction to execute a server task.'},{title:'When to open the project view',text:'The explicit action in the context panel opens the implementation page. Selecting the object itself only focuses it.'}]},
  {id:d.child+'-evidence',item:d.child,facet:'evidence',title:d.project+' / evidence notes',summary:'Distinguish an authored example from a measured result.',provenance:'synthetic' as const,source:'Synthetic walkthrough; no external services contacted',sections:[{title:'What is actually demonstrated',text:'Stable identity between views, validated navigation state, and source-owned content.'},{title:'What is not asserted',text:'No employer achievement, certification, deployed cloud resource or production service-level metric is claimed.'},{title:'Illustrative source',text:'The excerpt is displayed as text, not executed by this document.',language:'SQL',code:'SELECT source_id, COUNT(*) AS observations\nFROM curated_events\nGROUP BY source_id;'}]}
]);
export const atlas:ExplorerSpec={format:'datapass.explorer',version:1,title:'System atlas',description:'Four capabilities, several views, one selected context. A reusable pattern for portfolios, project documentation and technical product sites.',provenance:'synthetic',groups:[{id:'platform',label:'Cloud'},{id:'analytics',label:'BI'},{id:'modeling',label:'Models'},{id:'delivery',label:'Automation'}],facets:[{id:'skills',label:'Capabilities'},{id:'projects',label:'Projects'},{id:'evidence',label:'Evidence'}],items,documents,journey:domains.map(d=>d.id),scene:'atlas',overviewCamera:'overview'};
