import {useEffect} from 'react';
import {RoomShell} from '@sqlrooms/room-shell';
import {Button} from './fluent';
import {Database,ChartScatter,Code2,Workflow,Clapperboard,Braces,KanbanSquare,Download,PanelLeftClose,X,Network} from 'lucide-react';
import {roomStore,useRoomStore} from './store';
import {modules,createBrowserHost} from './core/host';
const embedded=new URLSearchParams(location.search).get('embed')==='1';
const icons=[Database,ChartScatter,Code2,Workflow,Clapperboard,Braces,KanbanSquare,Network];
export default function App(){
 const active=useRoomStore(s=>s.datapass.module),open=useRoomStore(s=>s.datapass.openModule),ready=useRoomStore(s=>s.room.initialized),error=useRoomStore(s=>s.datapass.error),setError=useRoomStore(s=>s.datapass.setError);
 useEffect(()=>{const media=matchMedia('(max-width: 900px)');const update=()=>roomStore.getState().layout.setCollapsed('catalog-area',embedded||media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 function exportDraft(){const s=roomStore.getState();createBrowserHost().saveDownload('mosaicstudio-draft.json',new Blob([JSON.stringify({format:'datapass.studio2.draft',version:1,module:s.datapass.module,layout:s.layout.config,pipeline:s.datapass.pipeline,board:s.datapass.cards,note:'Explicit export: pipeline source text and task titles are included. Dataset bytes and SQL result rows are not included. Import/restore of this whole draft is not yet implemented. Architecture artifacts use the Architecture module export menu.'},null,2)],{type:'application/json'}));}
 return <RoomShell roomStore={roomStore} className={'studio-root '+(embedded?'embedded':'')}><a className="skip-link" href="#studio-workspace">Skip to workspace</a><header className="app-header"><div className="brand-mark"><span>dp</span></div><div className="brand"><strong>datapass <span>mosaicstudio</span></strong><small>DATA APPLICATION WORKSPACE</small></div><div className="header-context">Studio 2 <span>/</span> Local workbench</div><span className="spacer"/><span className="runtime-state" data-testid="runtime-state"><i className={ready?'ready':''}/>{ready?'DuckDB ready':'Starting DuckDB'}</span><Button size="small" icon={<Download size={14}/>} onClick={exportDraft}>Export draft</Button></header>
 {error&&<div className="global-error" role="alert"><span>{error}</span><Button size="small" icon={<X size={14}/>} aria-label="Dismiss error" onClick={()=>setError(null)}/></div>}
 <div className="app-body"><nav className="module-rail" aria-label="Workspace modules">{modules.map((m,i)=>{const Icon=icons[i];return <button type="button" key={m.id} onClick={()=>open(m.id)} aria-label={m.title} aria-current={active===m.id?'page':undefined} className={active===m.id?'active':''} title={m.description}><Icon size={20}/><span>{m.id==='explore'?'Data':m.id==='pipeline'?'Pipeline':m.id==='stories'?'Stories':m.id==='explain'?'Concepts':m.id==='linked'?'Linked':m.id==='board'?'Board':m.id==='architecture'?'Archi':'SQL'}</span></button>;})}<span className="spacer"/><button aria-label="Toggle asset panel" title="Toggle assets" onClick={()=>{const layout=roomStore.getState().layout;layout.setCollapsed('catalog-area',!layout.isCollapsed('catalog-area'));}}><PanelLeftClose size={19}/><span>Assets</span></button></nav><main id="studio-workspace"><RoomShell.LayoutComposer/></main></div><footer className="status-bar"><span><i/>Local browser session</span><span>{modules.find(m=>m.id===active)?.engine}</span><span className="spacer"/><span>Source files stay unchanged &middot; no automatic publishing</span></footer>
 </RoomShell>;
}
